### ISSUE TITLE
Modded block config doesn't work

### ISSUE THREAD

**Issue by sisby-folk** [fxmorin/MoreCulling#100]
We've had some instances of moreculling culling faces of modded blocks in invalid ways:
![image](https://user-images.githubusercontent.com/55819817/194802122-128eefc9-49a6-4e70-ab10-73db539db431.png)

However, disabling the mod from the configuration list doesn't prevent this, and neither does deleting the whole list from the file and setting `useOnModdedBlocksByDefault` to false

Some examples of modded blocks with issues - ko-fi table, aurora's decorations shelf, yttr clamber block

**Comment by fxmorin** [comment]
Fixed in the upcoming release
