### ISSUE TITLE
Make 1.19.3 updates compatible with all 1.19 versions?

### ISSUE THREAD

**Issue by VeggeieDude** [fxmorin/MoreCulling#108]
Hi, I'm currently using 1.19.2 until other mods catch up to updating to 1.19.3. That may be a while, so I was wondering if you'd be willing to make the newest updates compatible with all 1.19 versions, or at least 1.19.2

**Comment by fxmorin** [comment]
Not possible since 1.19.3 is actually more like 1.20.0, mojang is just stupid and apparently has no idea how version numbers work anymore.
I did however backport the fix to 1.19.2 in v0.10.1
