### ISSUE TITLE
DashLoader Incompatibility

### ISSUE THREAD

**Issue by Noahfrechette** [fxmorin/MoreCulling#109]
crashes when placing Tom's Simple Storage Mod (Fabric)  blocks https://pastebin.com/kg4NRgKk

**Comment by fxmorin** [comment]
Looking into it. 
Seems somehow a final value is null. Which is pretty bad and im going to guess its on there end

**Comment by fxmorin** [comment]
Ohh @Noahfrechette It's DashLoader. I'll see if I can fix this one

**Comment by fxmorin** [comment]
https://github.com/TeamQuantumFusion/DashLoader/issues/29

**Comment by fxmorin** [comment]
Yay
