### ISSUE TITLE
Game crashes when trying to render hanging-signs

### ISSUE THREAD

**Issue by The-Blue-Goose** [fxmorin/MoreCulling#110]
I only tested this with hanging spruce signs, but I can assume the issue holds for other wood types. When you are re-directed to the launcher, this is the error message (exit code 255):
   The game crashed whilst rendering block entity
   Error: java.lang.IllegalArgumentException: Cannot get property class_2758{name=rotation, clazz=class java.lang.Integer, values= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in Block{minecraft:spruce_wall_hanging_sign}

Here is the crash report:
[crash-2022-12-14_17.38.50-client.txt](https://github.com/fxmorin/MoreCulling/files/10232747/crash-2022-12-14_17.38.50-client.txt)

**Comment by fxmorin** [comment]
thanks ill attempt to fix it

**Comment by fxmorin** [comment]
I've fixed it, it will be included in the next release

**Comment by fxmorin** [comment]
Should be fixed in v0.12.1
