### ISSUE TITLE
Support both 1.19.2 and 1.19.3 on latest release?

### ISSUE THREAD

**Issue by Scarlaid** [fxmorin/MoreCulling#111]
Myself have many reason to not going up to 1.19.3, mainly because some of my QoL mods aren't updated to 1.19.3
So if possible, I hope for a 1.19.2 support on the latest release of MoreCulling (and MoreCullingExtra)

If those optimizations weren't needed in 1.19.2 then understandable.

**Comment by fxmorin** [comment]
Unfortunately I don't have the time to do that, if someone is willing to port it for me than I would happily accept it.

**Comment by fxmorin** [comment]
Ask and you shall receive

**Comment by fxmorin** [comment]
https://github.com/fxmorin/MoreCulling/releases/tag/v0.12.2-1.19

**Comment by Scarlaid** [comment]
okay that was unexpected turn, thank you man
