### ISSUE TITLE
[1.19.2] Crash with Create

### ISSUE THREAD

**Issue by Dan4oby** [fxmorin/MoreCulling#115]
Crash with Create when placing `create:*_wall` block next to `create:*_window_pane`.
These blocks:
https://ibb.co/NtBv855

Crashlog:
[crash-2022-12-19_10.44.24-client.txt](https://github.com/fxmorin/MoreCulling/files/10256933/crash-2022-12-19_10.44.24-client.txt)

**Comment by fxmorin** [comment]
Please remove DashLoader and check if the issue persists
