### ISSUE TITLE
Sign culling crashes the client - Pose stack not empty crash

### ISSUE THREAD

**Issue by Dekamir** [fxmorin/MoreCulling#118]
Title self explanatory.
Allow a sign to cull by going behind it to recreate.

[modlist.txt](https://github.com/fxmorin/MoreCulling/files/10290858/modlist.txt)
[crash-2022-12-23_02.07.06-client.txt](https://github.com/fxmorin/MoreCulling/files/10290853/crash-2022-12-23_02.07.06-client.txt)
[latest.log](https://github.com/fxmorin/MoreCulling/files/10290855/latest.log)

**Comment by AlphaBladeX** [comment]
same for me, took a while to figure this out

**Comment by fxmorin** [comment]
Fixed in v0.12.4
