### ISSUE TITLE
Remove unneeded dependencies

### ISSUE THREAD

**Issue by HyperSoop** [fxmorin/MoreCulling#119]
[Take this version for example.](https://modrinth.com/mod/moreculling/version/v0.12.3)  
It suggests Lithium, Sodium, and Memory Leak Fix. This is completely wrong as this tag should only ever be applied to mods which your mod integrates with unlocking actual additional content.  
It requires Cloth Config API. This is terribly wrong as there actually isn't a requirement for it for the mod to run - it runs flawlessly without it. This also confuses many applications such as packwiz or ATLauncher forcing the user to install an actually unneeded dependency.

**Comment by offbeat-stuff** [comment]
The suggests is for mods that give better performance, you could also call it a bit of self advertising

**Comment by offbeat-stuff** [comment]
sodium is under recommends

**Comment by offbeat-stuff** [comment]
```diff
diff --git a/src/main/resources/fabric.mod.json b/src/main/resources/fabric.mod.json
index 41ae79d..7a3f315 100644
--- a/src/main/resources/fabric.mod.json
+++ b/src/main/resources/fabric.mod.json
@@ -30,17 +30,20 @@
   "depends": {
     "fabricloader": ">=0.14.10",
     "minecraft": ">=1.19.3",
-    "java": ">=17",
-    "cloth-config": ">=9.0.94"
+    "java": ">=17"
   },
   "recommends": {
     "memoryleakfix": "*",
-    "sodium": ">=0.4.5"
+    "sodium": ">=0.4.5",
+    "cloth-config": ">=9.0.94"
   },
   "suggests": {
     "memoryleakfix": "*",
     "lithium": ">=0.8.0"
   },
+  "breaks": {
+    "cloth-config": "<9.0.94"
+  },
   "custom": {
     "mc-publish": {
       "curseforge": 630104,
```

would this be sufficient?

**Comment by HyperSoop** [comment]
I think all mentions of any other mods should be removed, it's a confisung situation overall but anyway

**Comment by fxmorin** [comment]
In the latest build I moved sodium into suggests. I do recommend these mods as it has a large impact on performance

**Comment by HyperSoop** [comment]
It's just not how you'd excpect those fields to be used. Most users wouldn't even notice, but it would look weird for power users and developers who already know about the whole thing. You ideally should only use those fields for mods unlocking additional functionality

**Comment by HyperSoop** [comment]
(Why is cloth config a required dependency, still? It works fine without it)

**Comment by fxmorin** [comment]
does it?

**Comment by HyperSoop** [comment]
It appears MoreCulling has Cloth Config JiJd, so you should probably remove this as a required dependency and put it as "embedded" instead
