### ISSUE TITLE
Chunks turn invisible

### ISSUE THREAD

**Issue by TechPro424** [fxmorin/MoreCulling#122]
![huge_2022-12-29_13 31 19](https://user-images.githubusercontent.com/86620085/209922505-0094ce54-edd6-473e-a22f-ef0960a29e8c.png)

Chunks turn invisible when using moreculling and sodium together
Problem is solved by removing moreculling

**Comment by fxmorin** [comment]
Can you check if the problem still exists in v0.12.4
Also what version are you using?

**Comment by TechPro424** [comment]
> Can you check if the problem still exists in v0.12.4 Also what version are you using?

0.12.3
Will check in a few days as I am having exams

**Comment by fxmorin** [comment]
Check with v0.13.0 when you do check

**Comment by TechPro424** [comment]
![javaw 2023-01-07 20-44-17](https://user-images.githubusercontent.com/86620085/211157849-e4897c0c-c400-4647-81f8-023324741208.png)

Does happen

**Comment by fxmorin** [comment]
Are you using any other mods?

**Comment by antgly** [comment]
Happens to me in the villages which have a bunch of traders in them walking around. (1.19.3) - I get the bed randomly disappearing for a moment until I move when the traders are sleeping.

**Comment by antgly** [comment]
I am using the latest versions of FerriteCore, EntityCulling, and MoreCulling on a Minecraft 1.19.3 Fabric client and server. The server and client are both running the latest versions of Starlight, Sodium (client only), Indium, VMP, and Krypton. I am using the latest Fabric API and Fabric Server setup, which I have updated within the past couple of days. I am not using any shaders.

**Comment by fxmorin** [comment]
Can I get logs, there must be something in there

**Comment by antgly** [comment]
Sure! What's the best way to do it? If you can link me to a page, that would be helpful for me.

**Comment by fxmorin** [comment]
Just run the game, find an invisible chunk then send the log located at `.minecraft/logs/latest.log` here

**Comment by VeggeieDude** [comment]
I seem to get a milder version of this bug. For me, sometimes when I'm in a cave, blocks that are further than like about 30 blocks won't render and show only void. When i get closer though they render again.

And one time a whole hill wasn't rendering when I was looking a certain way. Turning my camera would fix it though unless I was looking at that specific angle that made the blocks not render again.

But these barely happen for me, and the hill one only happened one time for me.

I'm using 1.19.2 v0.13.0, I'll send my logs and a screenshot if it happens again when im home 👍

**Comment by fxmorin** [comment]
That is not done by MoreCulling. I don't cull chunks or frustrum @VeggeieDude

**Comment by VeggeieDude** [comment]
Ahh ok gotcha lol, ty.
Ya my guess is either sodium or lambabettergrass

**Comment by TechPro424** [comment]
Here's my log when the bug happened
I played 1 match on pvplegacy with the invisible chunks, and then left the server and quit the game
https://drive.google.com/file/d/1eJDORNWMp0XSn3jLIm57r2i4al3NCrqU/view?usp=sharing
Using Google Drive because neither mclo.gs or GitHub Gist were able to handle the log, it was too big

**Comment by Nocturnal-1** [comment]
hey I know how to fix the invisible chunks and other stuff. It's a bug with More Culling but if you don't want invisible chunks download Fast Load (Up to 1.19.2 sadly)
Fast Load: https://www.curseforge.com/minecraft/mc-mods/fastload

**Comment by Nocturnal-1** [comment]
![chrome_A5zQHbioy2](https://user-images.githubusercontent.com/122235306/212643014-02d77a95-afaf-4ff4-8483-9974705d46ea.png)

**Comment by TechPro424** [comment]
> hey I know how to fix the invisible chunks and other stuff. It's a bug with More Culling but if you don't want invisible chunks download Fast Load (Up to 1.19.2 sadly) Fast Load: https://www.curseforge.com/minecraft/mc-mods/fastload

I already have it, and the bug still happens

**Comment by TechPro424** [comment]
However, some OpenGL error is being spammed in my log when the bug happens (check the gdrive link), so maybe that might give the dev a clue?

**Comment by fxmorin** [comment]
Ya sorry been too busy to check the log yet

**Comment by TechPro424** [comment]
Any progress on this? (It's fine if not, take your time)

**Comment by fxmorin** [comment]
There must be a really cursed mod in there, those opengl issues are not caused by MoreCulling

**Comment by fxmorin** [comment]
That log was completely useless. I have a feeling that whatever is causing the problem is probably also the mod spamming your logs like its free real estate.
I recommend you try removing mods, groups at a time except more culling and try identifying the mod spamming your logs. There's a good chance thats the cause

**Comment by TechPro424** [comment]
Will try tomorrow

**Comment by fxmorin** [comment]
I have a suspicion it may be `openmcskins` since that mod does both http & opengl stuff

#### Known compatibility issues in your pack:
- cem & animatica (animatica does not support cem)

**Comment by fxmorin** [comment]
It's also possible that its a block with an invalid model

**Comment by TechPro424** [comment]
Did not happen today, strangely
Perhaps something in 0.12.5 fixed it?

**Comment by fxmorin** [comment]
Possible

**Comment by TechPro424** [comment]
It happened again today with MoreCulling 0.16.0 

The errors relating to this issue seem to start from line 2812

[2023-02-17-2.log](https://github.com/fxmorin/MoreCulling/files/10764672/2023-02-17-2.log)

**Comment by TechPro424** [comment]
@fxmorin 
Happened again with 0.16.0
Without OpenMCSkins this time
Log: https://mclo.gs/vgnefT9
Modlist: https://moddermore.net/list/0abc8f29a9

**Comment by fxmorin** [comment]
@TechPro424 This seems to be caused by another mods, causing some type of exception during the chunk render phase.
