### ISSUE TITLE
1.18.2 `More Culling requires version [[6.x.x,6.x.x]] of cloth-config, which is missing!`

### ISSUE THREAD

**Issue by SettingDust** [fxmorin/MoreCulling#123]
`cloth-config 6.2.62`
`moreculling-1.18.2-0.8.2`

**Comment by fxmorin** [comment]
You need to use cloth config v7 or higher

**Comment by SettingDust** [comment]
> You need to use cloth config v7 or higher

The newest version of cloth is 6.x on curseforge and modrinth

![图片](https://user-images.githubusercontent.com/19922286/210124126-2a42a1b9-aa4c-4a85-81f6-1b803f161898.png)
![图片](https://user-images.githubusercontent.com/19922286/210124142-e5f56a4b-ca8c-483e-998b-59d4df7b39ff.png)

**Comment by fxmorin** [comment]
ohh for 1.18, right. Thanks ill check this tomorrow
