### ISSUE TITLE
Issues with blockstate culling

### ISSUE THREAD

**Issue by RinixGG** [fxmorin/MoreCulling#124]
Hello! Leave block's side getting culled if there is stair nearby. I think it works same with all non-full blocks.
MC 1.19.2, MoreCulling 0.12.4
![2022-12-31_01 23 56](https://user-images.githubusercontent.com/73175330/210115628-63012fe6-6b9a-4ee8-a8d5-6e343b89eac2.png)

**Comment by VeggeieDude** [comment]
Hm, I don't get this problem myself. Maybe the resource pack you're using isn't compatible with More Culling?

**Comment by fxmorin** [comment]
I have no idea how that's possible. Can you check if removing your resource pack solves the issue?
If it does can you link the resource pack so that I can fix it. Otherwise please list all the mods you are currently using

**Comment by RinixGG** [comment]
> I have no idea how that's possible. Can you check if removing your resource pack solves the issue? If it does can you link the resource pack so that I can fix it. Otherwise please list all the mods you are currently using

I removed all resourcepacks but the issue is keeping.
![изображение](https://user-images.githubusercontent.com/73175330/210133952-56858b3b-d714-4c16-8bd2-04a3a15157c2.png)
Here is the list of mods:
![изображение](https://user-images.githubusercontent.com/73175330/210134030-0e895731-cb1f-44ab-a21e-aee1abf0162c.png)
![изображение](https://user-images.githubusercontent.com/73175330/210134043-73e48931-d1d6-40ee-96fe-261686d23114.png)
![изображение](https://user-images.githubusercontent.com/73175330/210134058-ed68c3e7-d501-4304-9beb-e271d0d654b5.png)
![изображение](https://user-images.githubusercontent.com/73175330/210134066-9f789d75-8389-49a1-bd3c-8e5124528a42.png)
![изображение](https://user-images.githubusercontent.com/73175330/210134073-6c641aeb-bc3a-4bcc-8350-64349297b15c.png)
![изображение](https://user-images.githubusercontent.com/73175330/210134077-b5857de5-5f81-4bcb-b960-bf60653f43d9.png)
![изображение](https://user-images.githubusercontent.com/73175330/210134081-fb4ca858-bc8d-4b8e-bb08-c6c3d7836c14.png)

**Comment by fxmorin** [comment]
Can you try figure out what mod causes the issue. There's a couple rendering mods in there that could be causing it

**Comment by Kikugie** [comment]
@fxmorin I have the same issue, so I'll give more details here instead of making new post.
I tested this on empty instance with only mods being MoreCulling and ModMenu. No resourcepacks as well.

Issue with leaves occurs with "Gap" culling type. Same happens for powder snow. It happens with stairs, slabs, stonecutter, carpets. Maybe other blocks as well.
![2023-01-01_00 55 54](https://user-images.githubusercontent.com/50152507/210157993-8515cb80-0491-48c5-a138-60b3df47c199.png)


Graphics card: RTX 3050 Ti laptop, driver v512.78 (considering recent issues with soduim and litematica, but this version doesn't have that issue)

**Comment by fxmorin** [comment]
Thanks that's useful

**Comment by RinixGG** [comment]
> Thanks that's useful

I'll give some information too. As for me the issue didn't appear at 'Gap' Culling type but appears at 'Depth' and 'Random'.
The screenshot above was made with the 'Depth' culling type. Here is the screenshot with 'Random'
![изображение](https://user-images.githubusercontent.com/73175330/210655004-8c14c455-067e-4f69-8d92-f46da1ee310d.png)
NVIDIA Driver Version: 525.60.11 ; Graphics card: NVIDIA GeForce GTX 1660 Ti

**Comment by RinixGG** [comment]
@fxmorin I've just found another bug. 
![изображение](https://user-images.githubusercontent.com/73175330/210760776-25219d9a-cbd4-45a5-be4c-1fa5d13f0d37.png)
After disabling the BlockState culling the issue disappeared:
![изображение](https://user-images.githubusercontent.com/73175330/210760929-e2e4b29d-0dff-4220-85ae-4632705940e6.png)

**Comment by fxmorin** [comment]
The vines are currently being looked into

**Comment by fxmorin** [comment]
Fixed in v0.13.0
