### ISSUE TITLE
Block state culling vine issue 

### ISSUE THREAD

**Issue by Ether717** [fxmorin/MoreCulling#127]
when using custom terrain such as Williams or Terralith with block state culling on vines block state are broken and become ghost blocks underneath until updated, also this mod is amazing 
![Screen Shot 2023-01-05 at 9 18 57 pm](https://user-images.githubusercontent.com/95562180/210790297-2ad42055-0ccc-4418-af59-2e68d60b40ce.png)

**Comment by fxmorin** [comment]
Alright thanks for reporting it. I'll look into it

**Comment by PweSol** [comment]
I seem to have this issue even without custom terrain. The vine simply needs to be placed on a block.
![unknown](https://user-images.githubusercontent.com/95942686/210883185-bf0288bc-ea33-4ebb-8959-9bc097353d57.png)

**Comment by jmadarg** [comment]
Experiencing the same problem when Block State Culling is on, but not only vines, but tall grass, lychen and sculk veins (sometimes)

![2023-01-05_20 55 57](https://user-images.githubusercontent.com/62086445/210902546-1dd60064-f38e-4574-bb49-ad0222c68311.png)

![2023-01-05_20 59 08](https://user-images.githubusercontent.com/62086445/210902617-9b10ca03-11ee-4455-bd7c-18a98ce46c28.png)

![image](https://user-images.githubusercontent.com/62086445/210902871-991b7767-93cb-499d-9df0-013a98edaf4c.png)

**Comment by fxmorin** [comment]
I'm well aware, im working on fixing the issue

**Comment by fxmorin** [comment]
Fixed in v0.13.0
