### ISSUE TITLE
Leaves Culling Depth Issue

### ISSUE THREAD

**Issue by PweSol** [fxmorin/MoreCulling#128]
In the mod CullLessLeaves, when depth is set to 1, the back of the first leave block is always visible while any other leave block behind it is properly culled. This way we still get a nice performance boost in areas like jungle while, and single leaves block don't look terrible.

But this does not seem to be possible in this mod. No matter which method or depth I try, it always looks like this:
![unknown](https://user-images.githubusercontent.com/95942686/210885511-5c89b193-274c-446c-93dd-6c99fc79f38f.png)

**Comment by fxmorin** [comment]
Mind giving an example of how it should look?

**Comment by fxmorin** [comment]
Also some leave culling changes where made in v0.13.0

**Comment by PweSol** [comment]
nvm, I think I was thinking about the way leaves look on the Bedrock Edition. Maybe I just used to have a resource pack that makes it look fuller, but now I don't.
