### ISSUE TITLE
im using 0.12.5 but still see though undergroud

### ISSUE THREAD

**Issue by cloudy1552** [fxmorin/MoreCulling#129]
im using 0.12.5 but still see though.
![2023-01-06_19 15 33](https://user-images.githubusercontent.com/121796704/210982867-4373fcc5-5299-4483-805c-5fd5af78364c.png)
when i turn off blockstate culling, this didnt happend.
im sorry to bothering you again.

_Originally posted by @cloudy1552 in https://github.com/fxmorin/MoreCulling/issues/126#issuecomment-1373438452_

**Comment by RinixGG** [comment]
#124

**Comment by fxmorin** [comment]
Fixed in v0.13.0
