### ISSUE TITLE
Issues with shulkerboxes because of Enhanced block entities

### ISSUE THREAD

**Issue by RinixGG** [fxmorin/MoreCulling#131]
Hello! MoreCulling 0.13.0, MC 1.19.2, Enhanced block entities 0.7.2
![2023-01-07_13 26 40](https://user-images.githubusercontent.com/73175330/211145837-192f933b-e49a-4e27-a8f5-f855f76c745c.png)
Screenshot was made on empty instance with no resourcepacks and only MoreCulling, ModMenu, Cloth Config, NoChatReports and Enhanced block entities.
This doesn't happen without EBE.

**Comment by fxmorin** [comment]
Very interesting, I will look into this later. Does this also happen if the shulker box is facing up in that position?

**Comment by RinixGG** [comment]
> Very interesting, I will look into this later. Does this also happen if the shulker box is facing up in that position?

Behavior of this issue is very similar to previous issue's behavior. Here some screenshots:
![2023-01-07_21 11 37](https://user-images.githubusercontent.com/73175330/211164688-b7e1df0b-351f-4f82-88d2-1f6e4bdd13eb.png)
![2023-01-07_21 11 42](https://user-images.githubusercontent.com/73175330/211164692-73d749b6-4de0-4728-8889-1f7593c5f8f1.png)

**Comment by RinixGG** [comment]
Some more screenshots
![изображение](https://user-images.githubusercontent.com/73175330/211164809-27fa0a22-08b4-4c62-823b-eb2ad08fda38.png)
![изображение](https://user-images.githubusercontent.com/73175330/211164814-242c6944-302c-469d-8e51-2800f3c379e9.png)

**Comment by RinixGG** [comment]
I think it happens because EBE makes some block entities use blocks models and this not provided in MoreCulling's code

**Comment by fxmorin** [comment]
Fixed in v0.14.0
