### ISSUE TITLE
Disabling blockstate culling grays out leaves culling options

### ISSUE THREAD

**Issue by Slooshie1** [fxmorin/MoreCulling#136]
As you can see, when you enable blockstate culling, the leaves culling options become grayed out, but they still work when set _before_ disabling blockstate culling (I set the leaves to fast before enabling blockstate culling and it is clearly still working on the 4-layer-deep wall of leaves I am looking at in the screenshot). Could this be fixed?
![image](https://user-images.githubusercontent.com/90230538/212568017-48903f40-6262-4edb-891a-f76d12713384.png)

**Comment by fxmorin** [comment]
Ehh I don't think this is caused by me. I think it may be caused by your modified sodium settings.
Can you check if this happens in the default vanilla settings

**Comment by fxmorin** [comment]
After checking, this is not a problem with MoreCulling. It's probably an issue with whatever sodium re-skin you are using

**Comment by Avtera** [comment]
bro fix this pls. give us option to enable leaves culling without needing the blocks culling to be enabled. what if we don't want to cull other block than leaves?

**Comment by JosefLitos** [comment]
this is indeed an issue of this mod, even when I'm not using Reeses sodium options, it is grayed out when the `BlockState Culling` is toggled:
![obrazek](https://github.com/FxMorin/MoreCulling/assets/54900518/c7103bc0-a298-4cf8-965e-153184f78969)
![obrazek](https://github.com/FxMorin/MoreCulling/assets/54900518/30050263-9e61-446c-a0c9-8381ffed4bd4)

**Comment by FxMorin** [comment]
Yes, this is on purpose. The leave culling uses that culling system.
