### ISSUE TITLE
Does not work with the Betterend mod

### ISSUE THREAD

**Issue by ImpSpy2** [fxmorin/MoreCulling#14]
Used the chorus block to test and the culling works fine with BCLib on its own but when you add Betterend the blockface does not get culled.

**Comment by fxmorin** [comment]
I'm guessing that the chorus plant comes from the betterend mod? That would make sense since I'm not done with the modded api support

**Comment by ImpSpy2** [comment]
That's probably the case, even though its the vanilla block I think betterend is changing the model. The fence culling and bamboo culling does not seem to work for me with More Culling on it's own so I will assume that Betterend does not cause any issues with this mod as I cannot test anything other than the chorus block.

**Comment by fxmorin** [comment]
Ehh what do you mean the other culling don't work on their own? They definitely do, what other mods are you using?

**Comment by ImpSpy2** [comment]
I have the mod running on its own so i don't think its a mod compatibility issue. Unless I'm misunderstanding what the mod is supposed to do, I think the top of the fence and end rod should be invisible? This is with a lantern placed on top of the fence and sea pickle on top of the end rod.
![fence](https://user-images.githubusercontent.com/61091635/172300792-4349f1a3-d837-400b-b71a-830714db1812.png)
![rod](https://user-images.githubusercontent.com/61091635/172300809-34fef912-f049-419c-a0b1-5b81b767a205.png)

I also tested in a bamboo jungle and the FPS was basically identical with and without the mod.
![With Mod](https://user-images.githubusercontent.com/61091635/172302515-774ec1c9-a347-4a8d-a05a-acd7c5151f1e.png)

![Without Mod](https://user-images.githubusercontent.com/61091635/172302525-49c0247c-b01b-4ecb-b5bd-ab719df2aebf.png)

**Comment by fxmorin** [comment]
The lantern on top of the fence should have worked. Again, the chorus test is the easiest one to do. Don't test FPS or whatever. Just fly in spectator inside of a chorus plant that's at least 2 together

**Comment by ImpSpy2** [comment]
It looks like the chorus culling works fine.
![Screenshot_20220607_064147](https://user-images.githubusercontent.com/61091635/172304594-cc33a123-39cf-4023-a3e9-b8e1e272632b.png)

**Comment by fxmorin** [comment]
Ya the mod is working fine, ill just have to change some conditions later
