### ISSUE TITLE
Bamboo culling in v0.15.0 doesn't seem to work

### ISSUE THREAD

**Issue by MCSmallCai** [fxmorin/MoreCulling#140]
Bamboo culling in v0.15.0 doesn't seem to work.Return to V0.14.0 and return to work

**Comment by fxmorin** [comment]
Ehh mind showing images?

**Comment by MCSmallCai** [comment]
![Uploading 2023-01-31_13.34.58.png…]()_

**Comment by MCSmallCai** [comment]
![Uploading 2023-01-31_13.34.35.png…]()

**Comment by MCSmallCai** [comment]
![Uploading 2023-01-31_13.34.58.png…]()

**Comment by fxmorin** [comment]
Ehh those images are not valid...

**Comment by MCSmallCai** [comment]
![Uploading 2023-01-31_13.34.58.png…]()

**Comment by MCSmallCai** [comment]
![2023-01-31_13 34 35](https://user-images.githubusercontent.com/121654450/216015301-fd3517e2-c95e-4a2b-ba28-3f05de540cea.png)
![2023-01-31_13 34 58](https://user-images.githubusercontent.com/121654450/216015308-0ee877c5-38f8-495b-8611-435458423a65.png)

**Comment by fxmorin** [comment]
This does not seem to be the case for me, does it still happen when you are using vanilla textures?
Also do you have the blockstate culling option enabled

**Comment by MCSmallCai** [comment]
Version 0.16.0 has been restored, thank you

**Comment by fxmorin** [comment]
oh alright
