### ISSUE TITLE
0.16.0 is culling textures beneath rails

### ISSUE THREAD

**Issue by coornio** [fxmorin/MoreCulling#143]
It would appear there's an oopsie in the matrix:

![2023-02-09_22 13 41](https://user-images.githubusercontent.com/11655762/217927203-a79d8eca-98e1-4fc6-8636-24046715abc8.png)

This wasn't an issue previously with 0.15.0. Could you have a look please?

**Comment by fxmorin** [comment]
Yup ill check

**Comment by fxmorin** [comment]
![2023-02-10_04 12 31](https://user-images.githubusercontent.com/28154542/218051412-fb20a505-5b04-461e-b72d-2ea36d938bf3.png)
I'm not having the same issue in my testing world. Are they vanilla rails, and does this still happen when using vanilla textures?

**Comment by coornio** [comment]
Okay, tested this, no issues with the vanilla textures. The one depicted in my example is John Smith Legacy, and it's made with optifine features, such as CIT, connected textures, etc. I'm running on Fabric, with some extra mods to make use of said features, like CITresewn. 

One other thing I noticed is that this bug can't be recreated in single player. I am not certain what changes.

**Comment by fxmorin** [comment]
Can you give me the resource pack you are using?

**Comment by coornio** [comment]
Since I can't directly link to the official page's download (and it's a bit buried there so you might miss it), I uploaded it to my mediafire: https://www.mediafire.com/file/43nb76xfstvo1l5/John+Smith+Legacy+1.19.2+v4.zip/file

Otherwise, visit [their homepage](https://www.johnsmithlegacy.co.uk/) and scroll down to the "Resource Pack History" bit, then a bit below you'll see a huge pile of yellow links, it's a scroll box, scroll inside of it to locate the 1.19.2 v4.

**Comment by coornio** [comment]
Have you had any luck in finding out what might be wrong? No rush of course, just checking in :D

**Comment by fxmorin** [comment]
Sorry don't have the time at the moment. I'm too busy with work

**Comment by O-d-i-n-n** [comment]
I have the same issue with ladders but on 1.19.3 and with Lithos resourcepack.
![2023-02-28_23 14 41](https://user-images.githubusercontent.com/67060551/222000309-52e708a6-bbb5-4dc6-85aa-35a12603edb5.png)

**Comment by Lolothepro** [comment]
I can confirm this bug.
