### ISSUE TITLE
[Suggestion] Integration of MoreCulling Extra in MoreCulling

### ISSUE THREAD

**Issue by xIntMarco** [fxmorin/MoreCulling#147]
It makes no sense to keep 2 mods separate, and I think it's also inconvenient to maintain them.
It would be more effective to integrate MoreCulling Extra into MoreCulling by allowing players to enable the "Extra" features in the mod configuration as well.

**Comment by fxmorin** [comment]
MoreCulling Extra uses a resource pack which I don't want loaded on MoreCulling. Currently also working on a couple features that I don't want in MoreCulling.
It's not that hard to maintain since the code in there basically never changes

**Comment by xIntMarco** [comment]
Can't you just put a button in the mod configuration that enables the extra functions? Or maybe you prefer to keep the 2 mods separate. In that case go ahead and close this page.
Thank you anyway for your reply.
Tradotto con DeepL https://www.deepl.com/app/?utm_source=android&utm_medium=app&utm_campaign=share-translation

**Comment by fxmorin** [comment]
I do plan on adding more to MoreCullingExtra, ive just been busy
