### ISSUE TITLE
Incorrect Iron Door culling in Multiplayer

### ISSUE THREAD

**Issue by BurrConnie** [fxmorin/MoreCulling#149]
Top face of the bottom half of the Iron Door incorrectly culls the blocks behind it in multiplayer. Any attempt to recreate the bug in Singleplayer have failed. Also doesn't show up when logging on to the same Multiplayer server in Vanilla.
Mods installed:
Quilted Fabric API, Mod Menu, Logical Zoom, MoreCulling, MoreCullingExtra

![2023-03-16_21 44 26](https://user-images.githubusercontent.com/114810287/225735837-e4668f12-0ad8-4430-979d-07a75b7419cc.png)
![2023-03-16_21 44 41](https://user-images.githubusercontent.com/114810287/225735843-75edf5da-5005-4aa9-89b6-8b95ecf03a1d.png)

**Comment by fxmorin** [comment]
Fixed internally. Will be in the next release

**Comment by fxmorin** [comment]
Fixed in 1.17.0
