### ISSUE TITLE
Mixin incompatibility with LibMultipart

### ISSUE THREAD

**Issue by Juuxel** [FxMorin/MoreCulling#15]
See Juuxel/VanillaParts#29 for the crash log. The issue is basically that MoreCulling `@Overwrite`s `Block.shouldDrawSide` while LibMultipart [tries to inject into it](https://github.com/AlexIIL/LibMultiPart/blob/211acc9a18aa04f0f2de082320b22504dd55f2d0/src/main/java/alexiil/mc/lib/multipart/mixin/impl/Client_BlockMixin.java#L29):

https://github.com/fxmorin/MoreCulling/blob/8fbbec7077bde4c7198f9c238b29e09179c41c96/src/main/java/ca/fxco/moreculling/mixin/Block_drawSideMixin.java#L23-L25

**Comment by fxmorin** [comment]
I'm still waiting for LibMultipart to either merge or close the 1.19 pull request so that I can make my compatibility

**Comment by ardissaps** [comment]
Does not seems to crash anymore. Tried with latest backport for 1.18.2.
![image](https://user-images.githubusercontent.com/82106625/182068023-7cc25de8-a141-4dd3-879d-bbf104bb194a.png)

**Comment by fxmorin** [comment]
As mentioned here: https://github.com/AlexIIL/LibMultiPart/issues/50
It will not crash but it will also not work as intended for LibMultipart
