### ISSUE TITLE
 Croptopia Culling error 作物盛景的果树剔除错误

### ISSUE THREAD

**Issue by Kino0208** [fxmorin/MoreCulling#161]
Croptopia module of partial fruit tree fruit leaf box culling error
![2023-05-12_19 15 02](https://github.com/fxmorin/MoreCulling/assets/76459545/0c57204b-8a28-48c9-8732-3d7cb511400b)
fabric optifabric+optifine does not have errors
iris+Sodium elimination error
Game version 1.18.2
Module version: moreculling-1.18.2-0.8.2
: Croptopia-1.18.2-FABRIC-2.1.2
iris/Sodium are both the latest versions

chinese：
fabric 使用optifabric+optifine 不存在错误
iris+Sodium 存在剔除错误
游戏版本1.18.2
模组版本：moreculling-1.18.2-0.8.2
：Croptopia-1.18.2-FABRIC-2.1.2
iris/Sodium都是最新版

**Comment by fxmorin** [comment]
Why was this closed?

**Comment by Kino0208** [comment]
> 

因为当初突然又不能确定是不是该模组的问题导致

Because it was suddenly not sure if it was a problem with the module
