### ISSUE TITLE
Some items in item frames have visible faces culled

### ISSUE THREAD

**Issue by muzikbike** [FxMorin/MoreCulling#163]
I'm not sure if it'd be possible to have some sort of check implemented to make sure the face to be culled is a certain distance far into the block (perhaps configurable via resource packs to accommodate custom item frame models?) before it actually ends up  being culled.

This effect can be seen with azaleas, sculk shriekers, composters and scaffolding. I've also been able to see it in cauldrons if we make them use the cauldron block model in item form.
![2023-05-14_16 49 45](https://github.com/fxmorin/MoreCulling/assets/52297970/f886d100-b835-4606-ad27-2446b4fca35b)
![2023-05-14_16 49 56](https://github.com/fxmorin/MoreCulling/assets/52297970/e0b10d41-a11c-42a3-bb41-9ed0b432bfa0)
![2023-05-14_16 50 04](https://github.com/fxmorin/MoreCulling/assets/52297970/3c77e339-75d3-41e7-a63f-8e56048c4a18)
![2023-05-14_16 50 08](https://github.com/fxmorin/MoreCulling/assets/52297970/0d6ae73b-66d2-4c87-ac97-46e6ae152d44)

**Comment by prototype464** [comment]
This is one of those bugs you see and it's so small it wouldn't be noticed by nearly anyone using this mod, and you wonder how the hell the issue author caught it in the first place, or if it'll actually be fixed because it's a small thing

Anyway, nice catch!

**Comment by fxmorin** [comment]
muzikbike is a culling expert.
This is something I might fix at some point, however im too busy to do that these days
