### ISSUE TITLE
Cull transparent trapdoors occluded by non-transparent trapdoors

### ISSUE THREAD

**Issue by muzikbike** [FxMorin/MoreCulling#166]
For example, in the central arrangement viewed from the angle shown, the faces of the oak trapdoor should preferably not be visible:
![2023-05-14_17 24 19](https://github.com/fxmorin/MoreCulling/assets/52297970/b10632c7-bad7-43f3-bf27-03c0b3a0398c)
![2023-05-14_17 24 38](https://github.com/fxmorin/MoreCulling/assets/52297970/9d38f860-5bd4-4f8a-9994-fa55277f93cd)
![2023-05-14_17 24 45](https://github.com/fxmorin/MoreCulling/assets/52297970/1fc3daf0-3de6-4c91-af4d-e1720773bd46)

**Comment by FxMorin** [comment]
Now in the latest release: https://github.com/FxMorin/MoreCulling/releases/tag/v0.21.0-1.20.x
