### ISSUE TITLE
[BUG] incompatibility with Sodium

### ISSUE THREAD

**Issue by SeaSon2002** [fxmorin/MoreCulling#17]
![image](https://user-images.githubusercontent.com/61407079/173073795-cb8420b8-c675-4a56-afef-d020da9cd4fd.png)
seed: -7801397800430326937
MC 1.18.2
mod installed:
More culling 0.1.4
Sodium 0.4.1
Fabric API v55.1
Mod Menu 3.2.2
Cloth config 6.2.62
Happened with Ice Block placed above a solid block
this bug does not affect ice block on water block

**Comment by offbeat-stuff** [comment]
@SeaSon2002 
for the time being
edit this file https://github.com/fxmorin/MoreCulling/blob/master/src/main/resources/data/moreculling/tags/blocks/dont_cull.json
and add ice to it

**Comment by fxmorin** [comment]
Fixed in v0.2.0

**Comment by SeaSon2002** [comment]
> @SeaSon2002 for the time being edit this file https://github.com/fxmorin/MoreCulling/blob/master/src/main/resources/data/moreculling/tags/blocks/dont_cull.json and add ice to it

thanks, i compiled the mod and it worked!



> Fixed in v0.2.0
ty ❤
