### ISSUE TITLE
Issues with Fire Bowls from BetterNether

### ISSUE THREAD

**Issue by quiqueck** [FxMorin/MoreCulling#173]
I am the author of BetterNether, and was contacted by someone with a culling issue (quiqueck/BetterNether#137). Upon testing I found that MoreCulling appears to introduce a problem with our custom meshes, in particular this one:

<img width="966" alt="image" src="https://github.com/fxmorin/MoreCulling/assets/280847/6048ff10-e6ac-4d4b-b0fa-197e1dc42eba">
<img width="966" alt="image" src="https://github.com/fxmorin/MoreCulling/assets/280847/e67027f4-bbb8-462b-ac80-d6e97b7684e7">

I would guess that the feet of the bowl present the issue. They have set a cullface for the bottom-face as you can see here:
https://github.com/quiqueck/BetterNether/blob/e2750dbff153c4cac0c5441fba44cb45761f9cc9/src/main/resources/assets/betternether/models/block/cincinnasite_fire_bowl_on.json#L88-L98

Is this an issue were MoreCulling does not process the model correctly, or do we have to change our model(s)?

While the report was made for 1.19.2, the Model is the same in most versions of the mod.

**Comment by NolanHewitt** [comment]
Can confirm this happens on my end as well. Hope a solution can be found.

**Comment by quiqueck** [comment]
In the meanwhile you can disable the culling for BetterNether as described here:
https://github.com/quiqueck/BetterNether/issues/137#issuecomment-1590615720

**Comment by fxmorin** [comment]
@quiqueck Sorry for the late reply. Ive been really busy these days.
This is most likely due to the cull shape not being done correctly within the block.

Explanation on how to fix it and other possible issues here: 
https://github.com/fxmorin/MoreCulling/wiki/Using-the-API#Fixing-culling-issues-on-modded-blocks

**Comment by quiqueck** [comment]
No worries, and thanks for the great wiki entry! I actually forgot about the CullShape property and was only checking the model files. So this helped a lot :)

**Comment by KylerNyhagen** [comment]
Issue appears to be the same for the Ink Bushes as well.

**Comment by NolanHewitt** [comment]
This issue occurs with the betternether repawner statues as well when you look at them from a few blocks below them.

**Comment by quiqueck** [comment]
FireBowls and Respawner will be fixed in the next release, however I could not reproduce the issue for any age state of the ink bush. Would you happen to have a screen grab of the problem?

**Comment by NolanHewitt** [comment]
![huge_2023-07-09_08 23 55-min](https://github.com/fxmorin/MoreCulling/assets/52480898/38c66bbd-2560-404c-b05f-0632086a7e5b)

Only happens with the fully mature ink bush version for me.
