### ISSUE TITLE
Incompatible with ModernFix

### ISSUE THREAD

**Issue by Zorklis** [fxmorin/MoreCulling#174]
[crash-2023-06-14_16.55.45-server.txt](https://github.com/fxmorin/MoreCulling/files/11746528/crash-2023-06-14_16.55.45-server.txt)
modernfix-fabric-5.0.0+mc1.20 not loading with MoreCulling - v0.18.0 for 1.20.1

**Comment by fxmorin** [comment]
Seems like a weird compatibility issue

**Comment by Zorklis** [comment]
Yes, deleting ModernFix fixed it, ironic enough.

**Comment by Zorklis** [comment]
Hope this is fixed soon

**Comment by fxmorin** [comment]
Honestly not sure whats causing the conflict

**Comment by Zorklis** [comment]
Are you able to re-produce it on your end?
It's still causes freezing on the latest versions of these mods: moreculling-1.20.1-0.19.0 & modernfix-fabric-5.6.1+mc1.20.1 ;
[crash-2023-08-10_19.07.53-server.txt](https://github.com/fxmorin/MoreCulling/files/12315003/crash-2023-08-10_19.07.53-server.txt)

**Comment by Madis0** [comment]
I cannot confirm on clientside at least, ModernFix 5.7.2 and MoreCulling 0.19.0.

**Comment by fxmorin** [comment]
MoreCulling should not be running on servers. Its client-side only
