### ISSUE TITLE
Incompatible with extendedclouds-1.2.2+1.20

### ISSUE THREAD

**Issue by Zorklis** [FxMorin/MoreCulling#176]
[crash-2023-06-15_18.24.43-client.txt](https://github.com/fxmorin/MoreCulling/files/11759996/crash-2023-06-15_18.24.43-client.txt)

**Comment by FxMorin** [comment]
Is this still an issue. A little weird since I made a patch for that in v0.15.0 but you seem to have gotten that error with v0.18.0

**Comment by FxMorin** [comment]
Could you test with v0.21.0?

**Comment by Zorklis** [comment]
I've moved onto 1.20.4 Minecraft and extended hasn't been updated since 1.20 nor does it support above versions; I'd say just close this issue and if anyone experiences it they will report it. Thanks for looking into it
