### ISSUE TITLE
Crash with Cull Less Leaves installed

### ISSUE THREAD

**Issue by Guerdi** [fxmorin/MoreCulling#178]
**Minecraft** : `1.20.1`
**Quilt Loader** : `0.19.1`
**More Culling** : `0.18.1`
**Cull Less Leaves** : `1.2.0`

More detailled crash report :
[crash-2023-06-23_01.54.34.8532-quilt_loader.txt](https://github.com/fxmorin/MoreCulling/files/11841312/crash-2023-06-23_01.54.34.8532-quilt_loader.txt)

**Comment by fxmorin** [comment]
Yes the mods are incompatible.
MoreCulling culles the leaves like cull less leaves, although it also has a bunch of different culling techniques

**Comment by Guerdi** [comment]
Weird, the 1.19 versions are compatibles without crash

**Comment by fxmorin** [comment]
Well the the config file specifically specifies the conflict
