### ISSUE TITLE
1.18.2 version glass will have a bug

### ISSUE THREAD

**Issue by candy999** [fxmorin/MoreCulling#18]
![huge_2022-06-13_22 31 29](https://user-images.githubusercontent.com/2743971/173377357-c093cf78-686b-46f3-80de-37f4b828f958.png)
![huge_2022-06-13_22 43 15](https://user-images.githubusercontent.com/2743971/173379853-5d57935c-95ec-47d4-b96e-ae56e0229c2c.png)

mod list:
alternate-current-mc1.18-1.3.0.jar
betterfpsdist-fabric-1.18-1.8.jar
c2me-fabric-mc1.18.2-0.2.0+alpha.7.0-all.jar
cloth-config-fabric-6.2.62.jar
CocoaInput-1.18-fabric-4.0.4.jar
cullleaves-2.3.2.jar
dashloader-4.0.0.jar
debugify-1.11.0-fabric-1.18.2.jar
dynamic-fps-2.1.0.jar
enhancedblockentities-0.6+1.18.2.jar
entityculling-fabric-mc1.18-1.5.1.jar
fabric-api-0.55.1+1.18.2.jar
fabric-language-kotlin-1.8.0+kotlin.1.7.0.jar
fabrishot-1.7.0.jar
ferritecore-4.2.1-fabric.jar
forcecloseloadingscreen-1.1.1.jar
FpsReducer2-fabric-1.18.2-2.0.jar
indium-1.0.3+mc1.18.2.jar
iris-mc1.18.2-1.2.5.jar
krypton-0.1.9.jar
lazydfu-0.1.2.jar
lithium-fabric-mc1.18.2-0.7.10.jar
memoryleakfix-1.18.2-0.3.5.jar
midnightlib-0.4.4.jar
modmenu-3.2.2.jar
moreculling-1.18.2-0.1.4-alpha.jar
notenoughcrashes-4.1.6+1.18.2-fabric.jar
particle-blocker-1.0.jar
purpurclient-1.18.2-3.jar
reeses_sodium_options-1.4.3+mc1.18.2-build.42.jar
smoothboot-fabric-1.18.2-1.7.0.jar
sodium-extra-0.4.5+mc1.18.2-build.42.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
starlight-1.0.2+fabric.89b8d9f.jar
WorldEditCUI-1.18.2+01.jar
Xaeros_Minimap_22.9.2_Fabric_1.18.2.jar
Zoomify-1.6.0.jar

**Comment by fxmorin** [comment]
Yes, MoreCulling is in Alpha, and I'm no longer maintaining the 1.18.2 version. Huge optimizations are being worked on, with API support although only for 1.19+
