### ISSUE TITLE
Warning when loading (still present in 1.20.1)

### ISSUE THREAD

**Issue by Zorklis** [FxMorin/MoreCulling#180]
Since https://github.com/fxmorin/MoreCulling/issues/170 was closed and in fact not "Fixed in v0.18.0". This is to list the issue.
https://user-images.githubusercontent.com/85455465/246157453-eb855c88-93e9-424d-99da-2a041a8dd992.jpg

**Comment by fxmorin** [comment]
Why would this be caused MoreCulling?

**Comment by fxmorin** [comment]
#170 was completely unrelated to your bug. It was about a console warning.
Please give me your logs so that I can check whats causing the issue

**Comment by Zorklis** [comment]
[launcher_log.txt](https://github.com/fxmorin/MoreCulling/files/11926452/launcher_log.txt)
Okay so I found out it's a conflict with the mod [Just Load](https://github.com/trufflezmc/just-load)

**Comment by FxMorin** [comment]
I guess don't use Just Load?
