### ISSUE TITLE
Armor trims (and CITs) not getting rendered when using Custom Item Frame Renderer

### ISSUE THREAD

**Issue by MATRIX-feather** [FxMorin/MoreCulling#181]
## Description
With custom renderer:
![2023-07-02_11 01 44](https://github.com/fxmorin/MoreCulling/assets/55654482/bf264322-6942-4ece-a0a4-216e9e871510)

Without custom renderer:
![2023-07-02_11 01 41](https://github.com/fxmorin/MoreCulling/assets/55654482/0c81278b-490b-48f6-8f5e-d1743753e70a)

## Loader and Mods
Loader:
quilt-loader-0.19.0-1.20.1

Mods:
<details>

| Index | Mod                                               | ID                                           | Version             | Type    | File Hash (SHA-1)                        | File(s)                                                                                 | Sub-File                                                                    |
|------:|---------------------------------------------------|----------------------------------------------|---------------------|---------|------------------------------------------|-----------------------------------------------------------------------------------------|-----------------------------------------------------------------------------|
|    93 | Cloth Config v11                                  | cloth-config                                 | 11.0.99             | Fabric  | 338b0968fb4746f2a1fc2d003d3f2a32d1b0c31  | <mods>/cloth-config-11.0.99-fabric.jar                                                  |                                                                             |
|     0 | cloth-basic-math                                  | cloth-basic-math                             | 0.6.1               | Fabric  |                                          | <mods>/cloth-config-11.0.99-fabric.jar                                                  | /META-INF/jars/basic-math-0.6.1.jar                                         |
|     1 | conditional mixin                                 | conditional-mixin                            | 0.3.2               | Fabric  |                                          | <mods>/moreculling-1.20-0.18.1.jar                                                      | /META-INF/jars/conditional-mixin-v0.3.2.jar                                 |
|    60 | Minecraft                                         | minecraft                                    | 1.20.1              | Builtin | fca7e92c19fa8b008f7a920d483c2d758eaac8c9 | <game>/.cache/quilt_loader/remappedJars/minecraft-1.20.1-0.19.0/client-intermediary.jar |                                                                             |
|    28 | MixinExtras                                       | com_github_llamalad7_mixinextras             | 0.2.0-beta.8        | Fabric  |                                          | <mods>/moreculling-1.20-0.18.1.jar                                                      | /META-INF/jars/mixinextras-fabric-0.2.0-beta.8.jar                          |
|    52 | Mod Menu                                          | modmenu                                      | 7.1.0               | Fabric  | 7d26ff2477ad8a083f11c1006a2b87ff1c121b62 | <mods>/modmenu-7.1.0.jar                                                                |                                                                             |
|    68 | More Culling                                      | moreculling                                  | 1.20-0.18.1         | Fabric  | 388ad05e95d8c317911a53d57fe960e68661c69a | <mods>/moreculling-1.20-0.18.1.jar                                                      |                                                                             |
|    24 | OpenJDK 64-Bit Server VM                          | java                                         | 20                  | Builtin |                                          | /usr/lib/jvm/zulu-20-amd64                                                              |                                                                             |
|    41 | Quilt Advancement API                             | quilt_advancement                            | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/advancement-6.0.3+1.20.1.jar                                 |
|    58 | Quilt Base API                                    | quilt_base                                   | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/qsl_base-6.0.3+1.20.1.jar                                    |
|    31 | Quilt Biome API                                   | quilt_biome                                  | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/biome-6.0.3+1.20.1.jar                                       |
|    87 | Quilt Block Content Registry API                  | quilt_block_content_registry                 | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/block_content_registry-6.0.3+1.20.1.jar                      |
|    80 | Quilt Block Entity API                            | quilt_block_entity                           | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/block_entity-6.0.3+1.20.1.jar                                |
|    85 | Quilt Block Extensions API                        | quilt_block_extensions                       | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/block_extensions-6.0.3+1.20.1.jar                            |
|    67 | Quilt Chat API                                    | quilt_chat                                   | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/chat-6.0.3+1.20.1.jar                                        |
|    23 | Quilt Client Command API                          | quilt_client_command                         | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/client_command-6.0.3+1.20.1.jar                              |
|    61 | Quilt Command API                                 | quilt_command                                | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/command-6.0.3+1.20.1.jar                                     |
|     4 | Quilt Crash Info                                  | quilt_crash_info                             | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/crash_info-6.0.3+1.20.1.jar                                  |
|    33 | Quilt Data Callback API                           | quilt_data_callback                          | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/data_callback-6.0.3+1.20.1.jar                               |
|    36 | Quilt Dimension API                               | quilt_dimension                              | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/dimension-6.0.3+1.20.1.jar                                   |
|     8 | Quilt Entity API                                  | quilt_entity                                 | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/entity-6.0.3+1.20.1.jar                                      |
|    70 | Quilt Entity Events                               | quilt_entity_events                          | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/entity_events-6.0.3+1.20.1.jar                               |
|    16 | Quilt Entity Networking API                       | quilt_entity_networking                      | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/entity_networking-6.0.3+1.20.1.jar                           |
|    37 | Quilt Entity Rendering API                        | quilt_entity_rendering                       | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/entity_rendering-6.0.3+1.20.1.jar                            |
|    21 | Quilt Item Content Registry API                   | quilt_item_content_registry                  | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/item_content_registry-6.0.3+1.20.1.jar                       |
|    42 | Quilt Item Extensions API                         | quilt_item_extensions                        | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/item_extensions-6.0.3+1.20.1.jar                             |
|    69 | Quilt Item Setting API                            | quilt_item_setting                           | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/item_setting-6.0.3+1.20.1.jar                                |
|    34 | Quilt Lifecycle Events                            | quilt_lifecycle_events                       | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/lifecycle_events-6.0.3+1.20.1.jar                            |
|    17 | Quilt Loader                                      | quilt_loader                                 | 0.19.0              | Quilt   | 3302044ba441087464052d37a0bc4872bec3a368 | <user>/.minecraft/libraries/org/quiltmc/quilt-loader/0.19.0/quilt-loader-0.19.0.jar     |                                                                             |
|    11 | Quilt Multipart Entity API                        | quilt_entity_multipart                       | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/multipart-6.0.3+1.20.1.jar                                   |
|    75 | Quilt Networking                                  | quilt_networking                             | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/networking-6.0.3+1.20.1.jar                                  |
|     7 | Quilt Point of Interest API                       | quilt_point_of_interest                      | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/point_of_interest-6.0.3+1.20.1.jar                           |
|    81 | Quilt Recipe API                                  | quilt_recipe                                 | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/recipe-6.0.3+1.20.1.jar                                      |
|    14 | Quilt Registry API                                | quilt_registry                               | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/registry-6.0.3+1.20.1.jar                                    |
|     2 | Quilt Registry Entry Attachment                   | quilt_registry_entry_attachment              | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/registry_entry_attachment-6.0.3+1.20.1.jar                   |
|    46 | Quilt Resource Loader                             | quilt_resource_loader                        | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/resource_loader-6.0.3+1.20.1.jar                             |
|    76 | Quilt Screen API                                  | quilt_screen                                 | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/screen-6.0.3+1.20.1.jar                                      |
|    48 | Quilt Status Effect API                           | quilt_status_effect                          | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/status_effect-6.0.3+1.20.1.jar                               |
|    62 | Quilt Surface Rule API                            | quilt_surface_rule                           | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/surface_rule-6.0.3+1.20.1.jar                                |
|    56 | Quilt Tags API                                    | quilt_tags                                   | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/tags-6.0.3+1.20.1.jar                                        |
|    49 | Quilt Testing API                                 | quilt_testing                                | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/testing-6.0.3+1.20.1.jar                                     |
|    90 | Quilt Tooltip API                                 | quilt_tooltip                                | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/tooltip-6.0.3+1.20.1.jar                                     |
|    15 | Quilt Vehicle API                                 | quilt_vehicle                                | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/vehicle-6.0.3+1.20.1.jar                                     |
|    77 | Quilt Villager API                                | quilt_villager                               | 6.0.3+1.20.1        | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/villager-6.0.3+1.20.1.jar                                    |
|    82 | Quilted Fabric API                                | quilted_fabric_api                           | 7.0.2+0.83.0-1.20.1 | Quilt   | 4d9de51f9b9746fe2d173cbfd7df34cb41ce6de6 | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  |                                                                             |
|    45 | Quilted Fabric API Base                           | quilted_fabric_api_base                      | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-api-base-7.0.2+0.83.0-1.20.1.jar                      |
|    18 | Quilted Fabric API Lookup API (v1)                | quilted_fabric_api_lookup_api_v1             | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-api-lookup-api-v1-7.0.2+0.83.0-1.20.1.jar             |
|    89 | Quilted Fabric Biome API (v1)                     | quilted_fabric_biome_api_v1                  | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-biome-api-v1-7.0.2+0.83.0-1.20.1.jar                  |
|    12 | Quilted Fabric Block API (v1)                     | quilted_fabric_block_api_v1                  | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-block-api-v1-7.0.2+0.83.0-1.20.1.jar                  |
|    84 | Quilted Fabric BlockRenderLayer Registration (v1) | quilted_fabric_blockrenderlayer_v1           | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-blockrenderlayer-v1-7.0.2+0.83.0-1.20.1.jar           |
|    65 | Quilted Fabric Client Tags                        | quilted_fabric_client_tags_api_v1            | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-client-tags-api-v1-7.0.2+0.83.0-1.20.1.jar            |
|    63 | Quilted Fabric Command API (v1)                   | quilted_fabric_command_api_v1                | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-command-api-v1-7.0.2+0.83.0-1.20.1.jar                |
|    25 | Quilted Fabric Command API (v2)                   | quilted_fabric_command_api_v2                | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-command-api-v2-7.0.2+0.83.0-1.20.1.jar                |
|    27 | Quilted Fabric Commands (v0)                      | quilted_fabric_commands_v0                   | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-commands-v0-7.0.2+0.83.0-1.20.1.jar                   |
|    39 | Quilted Fabric Containers (v0)                    | quilted_fabric_containers_v0                 | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-containers-v0-7.0.2+0.83.0-1.20.1.jar                 |
|    30 | Quilted Fabric Content Registries (v0)            | quilted_fabric_content_registries_v0         | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-content-registries-v0-7.0.2+0.83.0-1.20.1.jar         |
|    44 | Quilted Fabric Convention Tags API (v1)           | quilted_fabric_convention_tags_api_v1        | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-convention-tags-v1-7.0.2+0.83.0-1.20.1.jar            |
|    20 | Quilted Fabric Crash Report Info (v1)             | quilted_fabric_crash_report_info_v1          | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-crash-report-info-v1-7.0.2+0.83.0-1.20.1.jar          |
|    71 | Quilted Fabric Data Generation API (v1)           | quilted_fabric_data_generation_api_v1        | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-data-generation-api-v1-7.0.2+0.83.0-1.20.1.jar        |
|     9 | Quilted Fabric Dimensions API (v1)                | quilted_fabric_dimensions_v1                 | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-dimensions-v1-7.0.2+0.83.0-1.20.1.jar                 |
|    10 | Quilted Fabric Entity Events (v1)                 | quilted_fabric_entity_events_v1              | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-entity-events-v1-7.0.2+0.83.0-1.20.1.jar              |
|     6 | Quilted Fabric Events Interaction (v0)            | quilted_fabric_events_interaction_v0         | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-events-interaction-v0-7.0.2+0.83.0-1.20.1.jar         |
|     5 | Quilted Fabric Events Lifecycle (v0)              | quilted_fabric_events_lifecycle_v0           | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-events-lifecycle-v0-7.0.2+0.83.0-1.20.1.jar           |
|    64 | Quilted Fabric Game Rule API (v1)                 | quilted_fabric_game_rule_api_v1              | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-game-rule-api-v1-7.0.2+0.83.0-1.20.1.jar              |
|    54 | Quilted Fabric Item API (v1)                      | quilted_fabric_item_api_v1                   | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-item-api-v1-7.0.2+0.83.0-1.20.1.jar                   |
|    40 | Quilted Fabric Item Group API (v1)                | quilted_fabric_item_group_api_v1             | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-item-group-api-v1-7.0.2+0.83.0-1.20.1.jar             |
|    83 | Quilted Fabric Key Binding API (v1)               | quilted_fabric_key_binding_api_v1            | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-key-binding-api-v1-7.0.2+0.83.0-1.20.1.jar            |
|    59 | Quilted Fabric Key Bindings (v0)                  | quilted_fabric_keybindings_v0                | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-keybindings-v0-7.0.2+0.83.0-1.20.1.jar                |
|    88 | Quilted Fabric Lifecycle Events (v1)              | quilted_fabric_lifecycle_events_v1           | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-lifecycle-events-v1-7.0.2+0.83.0-1.20.1.jar           |
|    13 | Quilted Fabric Loot API (v2)                      | quilted_fabric_loot_api_v2                   | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-loot-api-v2-7.0.2+0.83.0-1.20.1.jar                   |
|    74 | Quilted Fabric Loot Tables (v1)                   | quilted_fabric_loot_tables_v1                | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-loot-tables-v1-7.0.2+0.83.0-1.20.1.jar                |
|    51 | Quilted Fabric Message API (v1)                   | quilted_fabric_message_api_v1                | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-message-api-v1-7.0.2+0.83.0-1.20.1.jar                |
|     3 | Quilted Fabric Mining Level API (v1)              | quilted_fabric_mining_level_api_v1           | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-mining-level-api-v1-7.0.2+0.83.0-1.20.1.jar           |
|    79 | Quilted Fabric Models (v0)                        | quilted_fabric_models_v0                     | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-models-v0-7.0.2+0.83.0-1.20.1.jar                     |
|    29 | Quilted Fabric Networking (v0)                    | quilted_fabric_networking_v0                 | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-networking-v0-7.0.2+0.83.0-1.20.1.jar                 |
|    47 | Quilted Fabric Networking API (v1)                | quilted_fabric_networking_api_v1             | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-networking-api-v1-7.0.2+0.83.0-1.20.1.jar             |
|    32 | Quilted Fabric Object Builder API (v1)            | quilted_fabric_object_builder_api_v1         | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-object-builder-api-v1-7.0.2+0.83.0-1.20.1.jar         |
|    50 | Quilted Fabric Particles (v1)                     | quilted_fabric_particles_v1                  | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-particles-v1-7.0.2+0.83.0-1.20.1.jar                  |
|    73 | Quilted Fabric Recipe API (v1)                    | quilted_fabric_recipe_api_v1                 | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-recipe-api-v1-7.0.2+0.83.0-1.20.1.jar                 |
|    78 | Quilted Fabric Registry Sync (v0)                 | quilted_fabric_registry_sync_v0              | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-registry-sync-v0-7.0.2+0.83.0-1.20.1.jar              |
|    38 | Quilted Fabric Renderer - Indigo                  | quilted_fabric_renderer_indigo               | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-renderer-indigo-7.0.2+0.83.0-1.20.1.jar               |
|    26 | Quilted Fabric Renderer API (v1)                  | quilted_fabric_renderer_api_v1               | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-renderer-api-v1-7.0.2+0.83.0-1.20.1.jar               |
|    55 | Quilted Fabric Renderer Registries (v1)           | quilted_fabric_renderer_registries_v1        | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-renderer-registries-v1-7.0.2+0.83.0-1.20.1.jar        |
|    91 | Quilted Fabric Rendering (v0)                     | quilted_fabric_rendering_v0                  | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-rendering-v0-7.0.2+0.83.0-1.20.1.jar                  |
|    86 | Quilted Fabric Rendering (v1)                     | quilted_fabric_rendering_v1                  | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-rendering-v1-7.0.2+0.83.0-1.20.1.jar                  |
|    22 | Quilted Fabric Rendering Data Attachment (v1)     | quilted_fabric_rendering_data_attachment_v1  | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-rendering-data-attachment-v1-7.0.2+0.83.0-1.20.1.jar  |
|    57 | Quilted Fabric Rendering Fluids (v1)              | quilted_fabric_rendering_fluids_v1           | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-rendering-fluids-v1-7.0.2+0.83.0-1.20.1.jar           |
|    19 | Quilted Fabric Resource Conditions API (v1)       | quilted_fabric_resource_conditions_api_v1    | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-resource-conditions-api-v1-7.0.2+0.83.0-1.20.1.jar    |
|    72 | Quilted Fabric Resource Loader (v0)               | quilted_fabric_resource_loader_v0            | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-resource-loader-v0-7.0.2+0.83.0-1.20.1.jar            |
|    35 | Quilted Fabric Screen API (v1)                    | quilted_fabric_screen_api_v1                 | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-screen-api-v1-7.0.2+0.83.0-1.20.1.jar                 |
|    66 | Quilted Fabric Screen Handler API (v1)            | quilted_fabric_screen_handler_api_v1         | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-screen-handler-api-v1-7.0.2+0.83.0-1.20.1.jar         |
|    43 | Quilted Fabric Sound API (v1)                     | quilted_fabric_sound_api_v1                  | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-sound-api-v1-7.0.2+0.83.0-1.20.1.jar                  |
|    92 | Quilted Fabric Transfer API (v1)                  | quilted_fabric_transfer_api_v1               | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-transfer-api-v1-7.0.2+0.83.0-1.20.1.jar               |
|    53 | Quilted Fabric Transitive Access Wideners (v1)    | quilted_fabric_transitive_access_wideners_v1 | 7.0.2+0.83.0-1.20.1 | Quilt   |                                          | <mods>/qfapi-7.0.2_qsl-6.0.3_fapi-0.83.0_mc-1.20.1.jar                                  | /META-INF/jars/fabric-transitive-access-wideners-v1-7.0.2+0.83.0-1.20.1.jar |

</details>

**Comment by iMoobert** [comment]
has this ever been addressed? I am having the same issue

**Comment by iMoobert** [comment]
Has this already been addressed? I'm having the same issue.

**Comment by fxmorin** [comment]
Been pretty busy lately and haven't been able to work on this mod. I plan on rewriting the custom renderer to attempt to support CIT's however that might be hard to do, as I need the control to cull specific faces of the models

**Comment by FxMorin** [comment]
This will be fixed in the next release
