### ISSUE TITLE
Crash when viewing Every Compat's items in EMI

### ISSUE THREAD

**Issue by Steveplays28** [FxMorin/MoreCulling#182]
## Log

[Log file (mclo.gs)](https://mclo.gs/O2RsmF6)

## Version info

- Minecraft `1.19.2` Quilt
- More Culling `1.19.1-0.17.0`
- EMI `1.0.5`
- Every Compat `1.19.2-2.4.11-fabric`

## Steps to reproduce

1. Enable all culling options in video settings (not sure which one causes the issue)
2. Open the inventory
3. Search for `@EveryCompat` in EMI
4. Observe the crash

## Linked issues

- https://github.com/emilyploszaj/emi/issues/231

**Comment by fxmorin** [comment]
Can you find which option causes the crash, not sure how this could be MoreCulling

**Comment by Steveplays28** [comment]
I apologise, I sent the wrong log. You need the one without Stack Deobfuscator, because something goes wrong on their side with mapping this crash.

Here's the [log without `stackdeobf` (mclo.gs)](https://mclo.gs/O2RsmF6). Updated the issue description.

**Comment by FxMorin** [comment]
This should be fixed in the next release

**Comment by Steveplays28** [comment]
Awesome, thank you.
