### ISSUE TITLE
MoreCulling issue w/ 3D Skin Layers

### ISSUE THREAD

**Issue by RisPNG** [fxmorin/MoreCulling#185]
MoreCulling when paired with 3D Skin Layers causes a graphical issue to the player model in the in-game inventory. Some parts of the head (hat layer) of the player model in the in-game inventory disappears. 

Image:
![javaw_Y2bhvhzaaZ](https://github.com/fxmorin/MoreCulling/assets/4275248/9197aaca-dbf1-4573-9ca9-a5b8d409f552)
![javaw_Z4qbx75iJ3](https://github.com/fxmorin/MoreCulling/assets/4275248/7b29b80b-a454-406f-bf21-a04ba6fff7d2)

**Comment by fxmorin** [comment]
Turn off the entity model culling

**Comment by RisPNG** [comment]
Is that the only solution?

![image](https://github.com/fxmorin/MoreCulling/assets/4275248/20171f19-ef28-4cbd-881f-f77c24b5da0a)

**Comment by fxmorin** [comment]
Im talking about the MoreCulling option.

**Comment by RisPNG** [comment]
This is the More Culling options, through the mod options. Even through the Sodium settings as well which has no such options.

**Comment by fxmorin** [comment]
Ehh it shouldn't let you enable it if you have sodium installed…
Can you send me your moreculling config file

**Comment by RisPNG** [comment]
> Ehh it shouldn't let you enable it if you have sodium installed…
> Can you send me your moreculling config file

it was already enabled when I have both Sodium and MoreCulling installed. I didn't touch it, but instead it doesn't let me disable it. I'll send the config file in a few hours. currently outside.

**Comment by RisPNG** [comment]
this was my moreculling,toml
```
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 48
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 0.0
leavesCullingMode = "DEPTH"
leavesCullingAmount = 1
includeMangroveRoots = true
powderSnowCulling = true
entityModelCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
minecraft = true
visualoverhaul = true
```

I just manually set "entityModelCulling" to false and everything is okay now. the entityModelCulling was already set to true when I have both Sodium and MoreCulling installed. Has the default set to false? if that's already done, then there's maybe some mistake on my part.

**Comment by fxmorin** [comment]
In the latest release I made so that its forced into false.
