### ISSUE TITLE
Option to enable leaves culling without needing the blocks culling to be enabled

### ISSUE THREAD

**Issue by Avtera** [FxMorin/MoreCulling#188]
Give us this option pls. What if we don't want to cull other blocks than leaves? at least if you don't make this change, stop your mod from giving incompatible warning/crash if the Cull Leaves Mod or Cull Less Leaves Mod is installed.

Thanks!

**Comment by fxmorin** [comment]
Thats not how this works.
I replace the block culling system when that option is enabled, it completely breaks other leaf culling mods. 
Why would you only want to cull leaves? The leaves are barely anything compared to the amount of faces removed front the block culling.

**Comment by Avtera** [comment]
If you were asking why and for what reason, that's like you asking why there are people who created a mod that cull the leaves only, and asking 300k+ people who downloaded the mod why they need to cull the leaves only.

Block culling isn't fully compatible with other mods, so that is why I still need this mod to cull things that other mods didn't do, to get more fps but not cause incompatibility with other mods (except for another culling mod).

Thanks for your understanding.

**Comment by fxmorin** [comment]
What mods are causing incompatibilities? 
I might be able to get it working without my backend however it wont be as effective
