### ISSUE TITLE
Intermittent crash when joining a server (possible incompatibility with JourneyMap)

### ISSUE THREAD

**Issue by SilentException** [FxMorin/MoreCulling#190]
When joining a server lobby, JWM will crash, logs attached with MoreCulling being on top of stack trace. JourneyMap is also in the stack trace so it might be incompatibility with that?
I experienced this multiple times yesterday after server resource pack was loaded,  joined lobby and would lock and crash instantly.
After few retries I couldn't reproduce anymore, maybe just bad timing.

[hs_err_pid35.log](https://github.com/fxmorin/MoreCulling/files/12443379/hs_err_pid35.log)
[latest.log](https://github.com/fxmorin/MoreCulling/files/12443380/latest.log)

**Comment by FxMorin** [comment]
Does this still happen with v0.20.3?

**Comment by SilentException** [comment]
I'm still on 1.20.1 but no, it didn't happen for quite some time now.
