### ISSUE TITLE
Beacon beam culling

### ISSUE THREAD

**Issue by Madis0** [FxMorin/MoreCulling#191]
Reference implementation: https://github.com/feytox/FeyTweaks

Other optimizations of that mod are probably unwanted

**Comment by fxmorin** [comment]
I keep being surprised by these things when I really shouldnt. Minecraft barely culls anything.
Ill make my own culling checks for beacons soon

**Comment by FxMorin** [comment]
Now in the latest release: https://github.com/FxMorin/MoreCulling/releases/tag/v0.21.0-1.20.x
