### ISSUE TITLE
Complementary Shaders' item frame Integrated PBR+ breaks with Custom Item Frame Renderer

### ISSUE THREAD

**Issue by Slooshie1** [FxMorin/MoreCulling#193]
When More Culling's Custom Item Frame Renderer is enabled in video settings, Complementary's item frame Integrated PBR+ feature does not work. Instead of the item or block inside the item frame being emissive like in the following picture...
![image](https://github.com/FxMorin/MoreCulling/assets/90230538/4f62ac9f-425d-4fe1-a799-101fedb8f8d8)
...it does not have any special PBR effects and renders like it's just any other normal item, like so:
![image](https://github.com/FxMorin/MoreCulling/assets/90230538/37aaa6e2-a1c7-4158-9b5c-bfa4fb306697)
This happens regardless of whether Frame LOD or 3-Face Frame Culling are enabled or disabled.

**Comment by FxMorin** [comment]
Yes im aware, just turn off the custom item frame renderer.
Not much I can do about it currently, and im too busy to work on it

**Comment by FxMorin** [comment]
Will be fixed in the next release
