### ISSUE TITLE
mod, disables optional textures from resource packs that are in the frame

### ISSUE THREAD

**Issue by kepkira** [FxMorin/MoreCulling#197]
Hi, I noticed that in this mode the custom texture from the resource pack, which is located in the frame, is disabled. Hope, U can fix is, good luck
![2023-12-21_00 33 24](https://github.com/FxMorin/MoreCulling/assets/154473051/5d405de4-18ed-4e6d-9c11-d7b6a9487383)
with mod
![2023-12-21_00 41 23](https://github.com/FxMorin/MoreCulling/assets/154473051/210d3bad-5cf3-4f69-bd2a-9ffd763f2204)
without

**Comment by FxMorin** [comment]
Yup this will be fixed in the next release
