### ISSUE TITLE
Multiple mod incompatibility

### ISSUE THREAD

**Issue by craftish37** [fxmorin/MoreCulling#2]
Hello sir, it's me again 😅
I downloaded your mod earlier in the day and well runs pretty smoothly... unless I try to break a block O_O
Here's the crash reports, as always, don't hesitate to ask for anything else �

[crash-2022-06-03_17.54.18-client.txt](https://github.com/fxmorin/MoreCulling/files/8834296/crash-2022-06-03_17.54.18-client.txt)
[crash-2022-06-03_18.55.27-client.txt](https://github.com/fxmorin/MoreCulling/files/8834298/crash-2022-06-03_18.55.27-client.txt)
�

**Comment by fxmorin** [comment]
Oh yup, that would do it. I knew some mod was going to make a custom model and ruin this.
I have an idea for a way to fix this, so ill try doing that

**Comment by fxmorin** [comment]
SO technically https://github.com/fxmorin/MoreCulling/commit/85a3cff588914c6752d7874323636a7bf648c098
Fixes the issue, although turns out Fabric-Api stops MoreCulling from culling more. Very cool, I shall open another issue

**Comment by craftish37** [comment]
https://user-images.githubusercontent.com/63811617/171933674-6c247fe5-eb63-4edb-ad7c-79ed8fca6c97.mp4

Well well well well
I compiled it from the master branch, seems like absolutely normal 🤣
I didn't chcek what you changed between versions, maybe should I x)

**Comment by fxmorin** [comment]
Lord almightly how. Also, I have actions so you don't need to compile them yourself. https://github.com/fxmorin/MoreCulling/actions/runs/2436282257

**Comment by fxmorin** [comment]
Just make sure it's not purpur or something since my mod should not modify the menu screen at all.

**Comment by craftish37** [comment]
Removed the only mod I updated since tests, then removed MoreCulling, worked as intended without :/

**Comment by fxmorin** [comment]
I don't even know tbh, is there anything in logs?

**Comment by craftish37** [comment]
Here you go 👀
[2022-06-03-6.log](https://github.com/fxmorin/MoreCulling/files/8835286/2022-06-03-6.log)

**Comment by fxmorin** [comment]
Goodness me thats a long log, although I believe I found the issue

**Comment by fxmorin** [comment]
Fixed in: https://github.com/fxmorin/MoreCulling/commit/a099a7527472edb87d77aff3dd7b6680b04943c9

**Comment by craftish37** [comment]
Well, more problems �
[latest.log](https://github.com/fxmorin/MoreCulling/files/8835859/latest.log)

**Comment by fxmorin** [comment]
Try https://github.com/fxmorin/MoreCulling/actions/runs/2437342482 once its done

**Comment by fxmorin** [comment]
Seems looms injected-interfaces works just as good as expected and did literally nothing

**Comment by craftish37** [comment]
[latest.log](https://github.com/fxmorin/MoreCulling/files/8838282/latest.log)
Fresh logs with the latest build 👌

**Comment by fxmorin** [comment]
Already aware of this: #7

**Comment by craftish37** [comment]
Oh, didn't see that, answered from my phone 😅
