### ISSUE TITLE
Pistons cause crash to desktop (exception ticking world)

### ISSUE THREAD

**Issue by steve-the-player** [FxMorin/MoreCulling#203]
[latest 2.log.zip](https://github.com/FxMorin/MoreCulling/files/13826690/latest.2.log.zip) note: this is a massive debug log! mclogs cuts off at 25'001 lines and ignores everything afterwards. Including the full file here in case it's related to the modlist)
[2024-01-04-1.log.gz](https://github.com/FxMorin/MoreCulling/files/13826706/2024-01-04-1.log.gz) (the autogenerated log of just the crash)

**Comment by jimchen5209** [comment]
Same here on 1.20.4 on powering on/off a piston, with only following mods installed:

- fabricloader 0.15.3
- cloth-config 13.0.121
- fabric-api 0.92.0+1.20.4
- lithium 0.12.1
- modernfix 5.11.1+mc1.20.4
- moreculling 1.20.1-0.19.0
- nbt_ac 1.1.8

Removing any of lithium, ModernFix, MoreCulling and NBTAutoComplete does not have this issue

[crash-2024-01-05_16.01.06-client.txt](https://github.com/FxMorin/MoreCulling/files/13839622/crash-2024-01-05_16.01.06-client.txt)

**Comment by AnikeiPS** [comment]
I have same problem with MoreCulling and ModernFix. It caused because of ModernFix dynamic cache generation update (`	at net.minecraft.class_4970$class_4971.redirect$hid000$modernfix$dynamicCacheGen(class_4970.java:5889) ~[client-intermediary.jar:?]`). Just downgrade ModernFix to 1.10.X version.

**Comment by FxMorin** [comment]
Will be fixed in the next release
