### ISSUE TITLE
Breaks and spams log with Sodium present

### ISSUE THREAD

**Issue by Madis0** [FxMorin/MoreCulling#204]
MoreCulling v0.20.1 on Minecraft 1.20.4
The log keeps looping the same injection failures for different blocks, game won't go past splash screen

https://mclo.gs/NwptN60

**Comment by Her0brineCreeper** [comment]
Can confirm, didn't happen with version 0.19.0 on Minecraft 1.20.4.

**Comment by FxMorin** [comment]
Fixed in v0.20.2: https://github.com/FxMorin/MoreCulling/releases/tag/v0.20.2-1.20.x
