### ISSUE TITLE
Incompatible with Sodium on 1.20.2

### ISSUE THREAD

**Issue by hotburger** [FxMorin/MoreCulling#205]
The game does not get past the mojang loading screen on 1.20.2. The only mods enabled are Sodium, More Culling, Mod Menu, and their dependencies. The game loads fine without Sodium.

https://mclo.gs/1AUnmEL

**Comment by FxMorin** [comment]
Fixed in v0.20.2: https://github.com/FxMorin/MoreCulling/releases/tag/v0.20.2-1.20.x
