### ISSUE TITLE
Crash on load/create world Sodium+FerriteCore

### ISSUE THREAD

**Issue by SylisMC** [FxMorin/MoreCulling#207]
Game crashes when trying to create or load an existing world

MC 1.20.1
Fabric loader 0.15.3

### Modlist

**Sodium -** mc1.20.1-0.5.3
**More Culling -** v0.20.1-1.20.x
**Cloth Config API -** 11.1.118+fabric
**Fabric API -** 0.91.0+1.20.1
**FerriteCore** - 6.0.1

**Main Menu Log**
[latest.log](https://github.com/FxMorin/MoreCulling/files/13851354/latest.log)
[crash-2024-01-06_15.37.59-client.txt](https://github.com/FxMorin/MoreCulling/files/13851353/crash-2024-01-06_15.37.59-client.txt)

for some reason without ferritecore the game sits at mojang logo with the bar at about 90-95% loaded for a good 30-60 seconds and generates 488,000+lines of text in the live log. causing it to be too large to upload to github or pastebin

### Additional Reports
these logs are from my full pack of performance / optifine alternative mods 

**Main Menu Log** (No crash yet but throwing errors 50+ mods loaded)
[latest.log](https://github.com/FxMorin/MoreCulling/files/13851088/latest.log)

**Load World Crash Log** (Same behavior when creating a new world 50+ mods loaded)
[latest.log](https://github.com/FxMorin/MoreCulling/files/13851211/latest.log)

**Comment by FxMorin** [comment]
Fixed in v0.20.2: https://github.com/FxMorin/MoreCulling/releases/tag/v0.20.2-1.20.x
