### ISSUE TITLE
Hates Quilt 0.23.0.

### ISSUE THREAD

**Issue by MagmaBro123** [FxMorin/MoreCulling#208]
Title.

[crash-2024-01-06_13.41.12-client.txt](https://github.com/FxMorin/MoreCulling/files/13851355/crash-2024-01-06_13.41.12-client.txt)
[latest.log](https://github.com/FxMorin/MoreCulling/files/13851357/latest.log)

Modlist in report.

**Comment by FxMorin** [comment]
Fixed in v0.20.2: https://github.com/FxMorin/MoreCulling/releases/tag/v0.20.2-1.20.x
