### ISSUE TITLE
[mc1.20.1] More Culling 0.20.1 compat mixin causing incompatibilities with FerriteCore and Sodium

### ISSUE THREAD

**Issue by input-Here** [FxMorin/MoreCulling#209]
Related to #204, #205, #207, #208

The recent 0.20.1 update has been causing crashes when loading into my world (I can confirm these don't occur in 0.19.0). My crashlog pointed towards FerriteCore’s [mixin](https://github.com/malte0811/FerriteCore/blob/1.20.0/Common/src/main/java/malte0811/ferritecore/mixin/dedupmultipart/MixinMultipartModel.java) into `net.minecraft.class_1095` as the issue, which I disabled. I was then able to load into my world but all grass blocks appeared as the missing texture. I found this error in my latest.log which is probably the cause (not 100% sure though) and suggests that the recent changes to the sodium multipart compat [mixin](https://github.com/FxMorin/MoreCulling/blob/master/src/main/java/ca/fxco/moreculling/mixin/compat/MultipartBakedModel_sodiumMixin.java) (which also mixes into the same class as ferritecore) are at fault.

> [20:42:35] [Chunk Render Task Executor #0/ERROR]: Mixin apply for mod moreculling failed moreculling.mixins.json:compat.MultipartBakedModel_sodiumMixin from mod moreculling -> net.minecraft.class_1095: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on onGetQuads could not find any targets matching

Relevant logs:
- [crash-2024-01-06_20.38.38-server.txt](https://github.com/FxMorin/MoreCulling/files/13851411/crash-2024-01-06_20.38.38-server.txt)
- [latest.log](https://github.com/FxMorin/MoreCulling/files/13851412/latest.log)

Modded information:
- Game version 1.20.1
- Fabric loader 0.15.3
- cloth-config-11.1.118-fabric
- dynamic-fps-3.3.2+minecraft-1.20.0
- enhancedblockentities-0.9+1.20
- entityculling-fabric-1.6.2-mc1.20.1
- fabric-api-0.91.0+1.20.1
- ferritecore-6.0.1-fabric
- ImmediatelyFast-Fabric-1.2.8+1.20.4
- indium-1.0.27+mc1.20.1
- lithium-fabric-mc1.20.1-0.11.2
- logical_zoom-0.0.20
- modernfix-fabric-5.11.1+mc1.20.1
- modmenu-7.2.2
- sodium-fabric-mc1.20.1-0.5.3
- threadtweak-fabric-1.20.2-0.1.1
- moreculling-1.20.4-0.20.1

**Comment by FxMorin** [comment]
Fixed in v0.20.2: https://github.com/FxMorin/MoreCulling/releases/tag/v0.20.2-1.20.x
