### ISSUE TITLE
Ice gives you x-ray

### ISSUE THREAD

**Issue by andreasdc** [fxmorin/MoreCulling#21]
When you place ice on the ground you can see throught the walls.

**Comment by fxmorin** [comment]
Already fixed. I'm not maintaining the 1.18 version anymore

**Comment by andreasdc** [comment]
> Already fixed. I'm not maintaining the 1.18 version anymore

Oh no, you know a way how to get the fix for 1.18 maybe?

**Comment by fxmorin** [comment]
Don't use the mod?

**Comment by Zensonaton** [comment]
Fixed version of the mod for 1.18.x: https://github.com/fxmorin/MoreCulling/releases/tag/v0.2.0-1.18
