### ISSUE TITLE
stuck on loading screen with more culling

### ISSUE THREAD

**Issue by t6rtar** [FxMorin/MoreCulling#210]
https://github.com/FxMorin/MoreCulling/assets/155864427/888a0bef-1075-4b77-923f-7928d1f09622

![image_2024-01-06_221543600](https://github.com/FxMorin/MoreCulling/assets/155864427/7c65e93b-fec1-4322-9502-dece6477c19f)
more culling enabled gets me stuck on loading screen
![image](https://github.com/FxMorin/MoreCulling/assets/155864427/dee98185-26a5-4e77-8ec8-2160f9fb8793)

**Comment by FxMorin** [comment]
Fixed in v0.20.2: https://github.com/FxMorin/MoreCulling/releases/tag/v0.20.2-1.20.x
