### ISSUE TITLE
New Verion [v0.21.0] Makes All potions Look like the same strength pots

### ISSUE THREAD

**Issue by Jasraj11** [FxMorin/MoreCulling#216]
New Verion [v0.21.0] Makes All potions Look like the same strength pots Downgrading To last version Fix it

**Comment by Madis0** [comment]
Initially I was not able to confirm it, but after a relaunch I could. Maybe something to do with cache?

**Comment by RedRat08** [comment]
i also get this

**Comment by FxMorin** [comment]
This is a bug due to old sodium optimization compatibility changes. However since the new system no longer replaces sodiums implementation ill remove the cache which broke.

**Comment by ItzSkyReed** [comment]
Have the same issue
