### ISSUE TITLE
Crash with ModernFix

### ISSUE THREAD

**Issue by Madis0** [FxMorin/MoreCulling#217]
Just clicked "Reset cache" on the settings of MoreCulling v0.21.0
https://mclo.gs/cK9iGX2

**Comment by FxMorin** [comment]
Seems to be caused by ModernFix

**Comment by embeddedt** [comment]
This occurs because the fake block model map used when ModernFix's dynamic model loading is enabled doesn't really expose the concept of a "list of loaded models". I can prevent this from crashing but there's no guarantee it will have the correct functionality.

**Comment by FxMorin** [comment]
@embeddedt Is there any way to solve this from MoreCulling's side?

**Comment by FxMorin** [comment]
Also can't you get a list of all dynamic models that you've loaded so far. As that would solve any functionality issues I get from your fix, and this doesn't get called often so it doesn't need to be fast.

**Comment by embeddedt** [comment]
Tracking which models are block models and which models are item models is quite inconvenient; also because I don't hold permanent strong references to models, there's no guarantee such a list would really contain every model that's currently in use.

**Comment by FxMorin** [comment]
Ya makes sense. Once I have time ill check how your implementation works and attempt a workaround.

**Comment by FxMorin** [comment]
Fixed in [v0.22.0](https://github.com/FxMorin/MoreCulling/releases/tag/v0.22.0-1.20.1%2B)
