### ISSUE TITLE
Campfires make block face under it invisible

### ISSUE THREAD

**Issue by ChrisTheBear** [FxMorin/MoreCulling#219]
In some directions, the campfire base shows no texture for what's underneath, meaning you can see underground

**Comment by Syvant** [comment]
Hi, chiming in to add that it occurs (at least for me) specifically when placing a campfire while facing east.

In the meantime, disabling BlockState Culling seems to resolve the issue.

**Comment by ChrisTheBear** [comment]
Yeah, same for me, I just took the mod off for now, maybe ill try it again and disable BlockState Culling
