### ISSUE TITLE
Do the Mod Cull Ice?

### ISSUE THREAD

**Issue by ardissaps** [fxmorin/MoreCulling#22]
When ice is above solid block while same height with water, it causes us to seee underground from the side of the ice behind.

**Comment by fxmorin** [comment]
Not in the latest versions, I am no longer maintaining the 1.18 builds

**Comment by Zensonaton** [comment]
Fixed version of the mod for 1.18.x: https://github.com/fxmorin/MoreCulling/releases/tag/v0.2.0-1.18
