### ISSUE TITLE
Item frames don't render after moving away and back

### ISSUE THREAD

**Issue by Madis0** [FxMorin/MoreCulling#223]
MoreCulling 0.22.0, MC 1.20.2

1. Enable custom item frame rendering
2. Place and look at some item frames
3. Move further away, like 50 blocks
4. Move back
5. Look at the item frames (they're invisible)

**Comment by FxMorin** [comment]
Are you able to reproduce this using only MoreCulling?

**Comment by Madis0** [comment]
Actually I was unable to reproduce it the second time regardless of MoreCulling. Will reopen when I find a way.
