### ISSUE TITLE
Serene Seasons Incompatibility

### ISSUE THREAD

**Issue by RedJ1ve** [FxMorin/MoreCulling#228]
When loading more culling and serene seasons together, the game crashes after booting up. Someone has also reported this to the seasons devs, who said it was a mixin conflict and suggested making an issue here aswell. I've also added a log using only serene seasons and their dependencies.

Serene Seasons Issue: https://github.com/Glitchfiend/SereneSeasons/issues/452

Crash log: [crash-2024-02-15_17.51.49-client.txt](https://github.com/FxMorin/MoreCulling/files/14300596/crash-2024-02-15_17.51.49-client.txt)

**Comment by vico93** [comment]
Comment from @Abdubbz (SereneSeasons maintainer) about the issue:
![image](https://github.com/FxMorin/MoreCulling/assets/3485505/be8f8d74-8dce-49eb-bc40-c86c56723b32)

**Comment by vico93** [comment]
Er.. any updates about it?

**Comment by FxMorin** [comment]
I left a comment on their issue. I havent gotten the time to fix it.

**Comment by nailuj9002** [comment]
soo are we getting it fixed?

**Comment by nailuj9002** [comment]
nvm i saw that it's on a different update but this fix is missing on the 1.20.1 version which is literally the most used version for modding rn
