### ISSUE TITLE
Trapdoors makes blocks behind them transparent

### ISSUE THREAD

**Issue by Kropidlak** [FxMorin/MoreCulling#229]
I've noticed that if I put a trapdoor adjacent to a block, it becomes transparent and using another trapdoor with "window" I can see through walls. The issue became more obvious when I loaded 3D models for trapdoors (I used models from vanillaweaks.net). Then i could see through a wall straight out the trapdoor with a gap.
![2024-02-23_14 47 19](https://github.com/FxMorin/MoreCulling/assets/161043399/1ea846c5-712e-4aef-be8f-4bc16f887803)
![2024-02-23_14 45 53](https://github.com/FxMorin/MoreCulling/assets/161043399/d6958a9f-7dee-4d29-8731-5210530d32b0)
![2024-02-23_14 45 58](https://github.com/FxMorin/MoreCulling/assets/161043399/cc110b0c-6ec6-4275-bd72-1066d363dbf0)
![2024-02-23_14 47 15](https://github.com/FxMorin/MoreCulling/assets/161043399/494c76d9-13f0-4249-9f9e-ee554d17e4c1)

**Comment by thebertster** [comment]
This issue has been raised already and is being investigated under #225

**Comment by mpustovoi** [comment]
Btw, mangrove trapdoor looks kinda cool with that
