### ISSUE TITLE
version above 0.19.0 won't work with Optifine (OptiFabric), 1.20.4

### ISSUE THREAD

**Issue by cyriotic3** [FxMorin/MoreCulling#239]
it seems that versions above MoreCulling 0.19.0 for 1.20.x crashes the game with Optifine (OptiFabric) on 1.20.4, I'm using Pojav so if it's the app or what since i do not have a PC to test that on, but I've provided the log, thank you in advance! :)
[latestlog.txt](https://github.com/FxMorin/MoreCulling/files/15052199/latestlog.txt)

**Comment by FxMorin** [comment]
Not going to fix it. Optifine is literal garbage, im not going to waste my time fixing it.
