### ISSUE TITLE
Severe rendering problems when there is ice

### ISSUE THREAD

**Issue by KyleUltimate** [fxmorin/MoreCulling#24]
yeah... smth is very wrong
![image](https://user-images.githubusercontent.com/68589851/175282594-8b0f9430-f219-4a8c-aebf-9bc0eb96be7c.png)
using nothing but moreculling in 1.18.2 + quilt

**Comment by fxmorin** [comment]
Known, it's an issue in the 1.18.2 release. It's been fixed in 1.19, I currently don't have time to backport the changes
