### ISSUE TITLE
More Culling Extras crashes the game

### ISSUE THREAD

**Issue by sniffercraft34** [FxMorin/MoreCulling#240]
So, this isn't about the MoreCulling mod, it's about MoreCulling extra. 
The MoreCulling mod works fine on its own, but with MoreCulling Extra makes your game crash, but it doesn't really say much, only that your game crashed. I removed MoreCullingExtra, and it worked fine.

**Comment by FxMorin** [comment]
Logs?

**Comment by sniffercraft34** [comment]
Sorry, the game doesn't display any logs really, it only says that the game crashed and they were sorry for the incovinience.

**Comment by FxMorin** [comment]
Unsure if I will be maintaining MoreCulling extra. Currently doesn't work

**Comment by sniffercraft34** [comment]
Ok, thx for the help
