### ISSUE TITLE
Error when loading companion plugin class

### ISSUE THREAD

**Issue by Oxeus** [FxMorin/MoreCulling#242]
It looks like a request to extent a class from Fallen-Breath/conditional-mixin is throwing an error in the code for this mod. 

The game does not crash otherwise.

log from error attached
[error.log](https://github.com/FxMorin/MoreCulling/files/15140704/error.log)

**Comment by AViewFromTheTop** [comment]
Same here.

**Comment by FxMorin** [comment]
Ill look into it

**Comment by FurnyGo** [comment]
same (0.25.0 mod, 1.20.6 minecraft)

**Comment by Sonhub51** [comment]
same

**Comment by emneo-dev** [comment]
Still a thing in 0.26.0

**Comment by FxMorin** [comment]
This has been fixed in `1.0.0-beta.1` and will be in `1.0.0`
