### ISSUE TITLE
Crash when loading 1.20.5?

### ISSUE THREAD

**Issue by muzikbike** [FxMorin/MoreCulling#245]
I can't check to see if #95 is fixed now...

[crash-2024-05-03_14.49.55-client.txt](https://github.com/FxMorin/MoreCulling/files/15201538/crash-2024-05-03_14.49.55-client.txt)

**Comment by FxMorin** [comment]
Your crash doesn't seem to have a mods list. Are you using the latest fabric API?

**Comment by muzikbike** [comment]
Nothing seems to be crashing anymore, no idea what was up with that. Loads fine in 1.20.6 now.
