### ISSUE TITLE
Improved block state culling does not appear to work anymore

### ISSUE THREAD

**Issue by muzikbike** [FxMorin/MoreCulling#249]
Tested with and without mods and resource packs. Culling for bamboo and for chorus plants just doesn't appear to be happening anymore.

![2024-05-23_21 42 49](https://github.com/FxMorin/MoreCulling/assets/52297970/6b08bf28-96dd-4c81-af0d-bc896071ccbc)
![2024-05-23_21 43 15](https://github.com/FxMorin/MoreCulling/assets/52297970/90fb48f3-3e71-4c49-8ab7-c00ad09503e1)
![2024-05-23_21 43 19](https://github.com/FxMorin/MoreCulling/assets/52297970/55255fa6-76f0-4d09-8d65-974f22fec9bf)

**Comment by FxMorin** [comment]
Is this in 1.20.5+
Looks like it might be due to a mixin failing

**Comment by muzikbike** [comment]
Yes.

**Comment by FxMorin** [comment]
Seems to be working in the 1.21 build, so not sure what happened there
