### ISSUE TITLE
Incorrect 3D Trapdoor culling.   1.20.6

### ISSUE THREAD

**Issue by Xaaali** [FxMorin/MoreCulling#252]
![2024-05-29_21 26 32](https://github.com/FxMorin/MoreCulling/assets/164149081/166eef90-e6d4-44f3-b242-b269df5f27b0)
![2024-05-29_21 26 45](https://github.com/FxMorin/MoreCulling/assets/164149081/7026b13a-329a-4443-8f4d-4a10cc77ce6f)

Block State Culling seems to be incorrectly culling blocks behind 3D trap doors (All variants), as supplied by the resource pack. Turning the option off resolves the issue, but doesnt seem like a good long term solution, due to performance impact.

This doesnt happen for other 3D models in the resource pack, such as closed doors, ladders. etc.

Resource pack shown is Vanilla Tweaks for 1.20.6.

**Comment by TheRedstoneShark** [comment]
I'm having the exact same issue with another 3d doors resource pack, "[Door Tweaks](https://modrinth.com/resourcepack/door-tweaks)" (using 1.20.4)

I've found that for both Vanilla Tweaks and Door Tweaks: Grass Blocks, Podzol, Myceilium, Dirt, Rooted Dirt, Stone, Deepslate, Netherrack, and Sand are not affected by the rendering bug, you can't see through them. (Also, there are probably more I haven't tested.)

**Comment by tajemniktv** [comment]
Similiar case - but sadly not only flapped trapdoors are being culled, but also glass for some reason
![image](https://github.com/user-attachments/assets/72fac645-20a2-43e4-bd90-828a4ecaca71)
additionaly (Well, I'd expect it to be a feature, not a bug) x-ray mods are only showing visible side of blocks
![image](https://github.com/user-attachments/assets/a03c3d9b-af5d-4582-bf02-a5ca275f34f5)

**Comment by FxMorin** [comment]
This was hackfixed in 0.26.0

**Comment by tajemniktv** [comment]
@FxMorin 
Not sure if by hackfixed you mean something what you said in other thread, like a "sloppy" fix, but sadly it still happens in 1.21 (0.26.0)
![image](https://github.com/user-attachments/assets/d4d846ef-64ac-48b2-9196-f8b28c6490a8)

**Comment by tajemniktv** [comment]
Edit: It... fixed itself? Damn, I have no clue what I did exactly, but the issue is gone...

**Comment by FxMorin** [comment]
The issues you are getting are really weird, like with the glass

**Comment by tajemniktv** [comment]
I bet they are weird... Tho I explicitly remember that I updated to Sodium 0.6 and Iris 1.8, enabled blockstate culling and... it was gone. Downgraded to Sodium 0.5 and Iris 1.7... and the issue did not reappear... Very odd XD

**Comment by FxMorin** [comment]
Seems to be fixed, ill reopen it if anyone gets the issue

**Comment by SkeleBones** [comment]
![image](https://github.com/user-attachments/assets/9e9d65d6-e08d-4d4f-b10f-f43c4f7dadc6)
I have the issue.

**Comment by SkeleBones** [comment]
![image](https://github.com/user-attachments/assets/7761949c-6419-4e2d-b1e2-8f66fb512a64)
Only on these trap doors though.
