### ISSUE TITLE
Can this mod be used on servers?

### ISSUE THREAD

**Issue by Legendmanj** [FxMorin/MoreCulling#253]
Can this mod be used on the server and not the client to have the same impact of not rendering things that the player can't see?
if yes, please let me know
if no, can it please be implemented to have a performance improvement on the server?

Thank You

**Comment by LordEnder-Kitty** [comment]
That is just not how that works. All rendering is client side only. The only way to make the server able to tell the client not to render something, like the invisibility effect, the client is just checking if the player has invisibility and the server is probably just sending player data to the client, but it has nothing to do with the actual rendering.

**Comment by FxMorin** [comment]
^ Its client-side only
