### ISSUE TITLE
Item frame back culling no longer seems to work either

### ISSUE THREAD

**Issue by muzikbike** [FxMorin/MoreCulling#255]
The frame itself is culled, but the contained block is not. (1.20.6)
![2024-06-06_07 53 04](https://github.com/FxMorin/MoreCulling/assets/52297970/f46d6099-59db-49b2-8db7-d4e10e940a72)
![2024-06-06_07 53 08](https://github.com/FxMorin/MoreCulling/assets/52297970/21e3c4b3-9dc0-4401-88e9-309fac7f9443)

**Comment by FxMorin** [comment]
Ill try to find the time to fix this at some point.
