### ISSUE TITLE
1.21/1.21.1 update

### ISSUE THREAD

**Issue by adr278** [FxMorin/MoreCulling#256]
it's that time again

**Comment by IzeAack** [comment]
[compile this for 1.21](https://github.com/CommandGenius/MoreCulling): https://github.com/CommandGenius/MoreCulling

**Comment by Evlyman** [comment]
> [скомпилируйте это для 1.21](https://github.com/CommandGenius/MoreCulling) : https://github.com/CommandGenius/MoreCulling

Hello, can you send me the already compiled version, please?

**Comment by adr278** [comment]
> > [скомпилируйте это для 1.21](https://github.com/CommandGenius/MoreCulling) : https://github.com/CommandGenius/MoreCulling
> 
> Hello, can you send me the already compiled version, please?
https://github.com/adr278/MoreCulling.git

**Comment by IzeAack** [comment]
> > [скомпилируйте это для 1.21](https://github.com/CommandGenius/MoreCulling) : https://github.com/CommandGenius/MoreCulling
> 
> Hello, can you send me the already compiled version, please?

Yes I do https://github.com/FxMorin/MoreCulling/actions/runs/9844630252

**Comment by Legendmanj** [comment]
bump

**Comment by IzeAack** [comment]
Hey, you can close you're issue https://modrinth.com/mod/moreculling/version/0.26.0
