### ISSUE TITLE
Forge compatibility 

### ISSUE THREAD

**Issue by Arch23-tech** [FxMorin/MoreCulling#260]
Plz in the name of God ... I hope the creator someday port this jaw breaking mod to forge so that those using embeduim and rebiduim can enjoy... porting it from 1.20.1 up to 1.21 .

Thank you for developing this mod anyways.

**Comment by ActuallyTheOwner** [comment]
Please do not port this to forge.
There are a lot of controversies with forge, forge is closed source as well.
Neoforge is better to port to if a secondary port is made!

**Comment by FxMorin** [comment]
I will not be porting it to a dead platform

**Comment by Arch23-tech** [comment]
That's fine (brute force rendering culling) mod is now a complete replacement mod of yours.....

And fortunately your mod has lots of incompatibilities especially with other optimization mods.

I hope you never port it to forge and and neoforge 😆😁😄😃😀😂🤣
