### ISSUE TITLE
Translucent items are invisible when held.

### ISSUE THREAD

**Issue by Moonyol** [FxMorin/MoreCulling#263]
Items that are translucent are invisible in 1st person when held, these include stained glass, stained glass panes, tinted glass, and ice.

moreculling-1.20.4-0.24.0.jar
fabric-api-0.97.1+1.20.4.jar
cloth-config-13.0.121-fabric.jar
fabric-loader-0.15.11-1.20.4

![image](https://github.com/user-attachments/assets/26ce1d5c-1dbf-402f-8d4b-49efae16e894)

**Comment by CommandGenius** [comment]
This is fixed in 1.21, though very sloppily.
