### ISSUE TITLE
Mod deletes itself from the mods folder every so often regardless of version + crash

### ISSUE THREAD

**Issue by Tsunai001** [FxMorin/MoreCulling#266]
I just wanna know why it does this, Reinstalling it is annoying

**Comment by Tsunai001** [comment]
erm actually now its doing this (v1.20.4, with more culling extra too)
[crash-2024-07-18_19.52.54-client.txt](https://github.com/user-attachments/files/16281248/crash-2024-07-18_19.52.54-client.txt)

**Comment by FxMorin** [comment]
Remove MoreCulling Extra. I haven't had the time to update it

**Comment by Tsunai001** [comment]
alright, thank you
