### ISSUE TITLE
CIT - Item frame remove CIT when using custom item renderer

### ISSUE THREAD

**Issue by Agent00Ming** [FxMorin/MoreCulling#27]
The new item frame culling breaks custom item textures that require an item's NBT data. This affects users of 'CIT Resewn' ~~and possibly 'Chime' as well~~. *Chime's custom item models work as intended*

~~I am aware that this is a very niche case and it would be nice if it was possible to add options for culling.~~ *Versions 0.5.0+ can be configured*
 
 Below is an example of what happens when I put a diamond pickaxe that has a custom item texture based on an enchantment applied to it and the exact same pickaxe in the item frame.
![2022-07-03_21 19 53](https://user-images.githubusercontent.com/107314235/177066643-b2d1b34d-f221-4700-84c2-ca14eeb3d4cb.png)

**Comment by fxmorin** [comment]
ill look into this, thanks for reporting it

**Comment by NovaXCIV** [comment]
> @NovaXCIV What do you mean by that?

![image](https://user-images.githubusercontent.com/104044556/177620942-3f6d444e-d6c5-4411-a882-314b2d8f4d52.png)

This sword ha a custom skin with the CIT feature of Optifine

**Comment by fxmorin** [comment]
Ya so I've identified the problem. I will release MoreCulling v0.5.0 which comes with the ability to toggle each optimization.
Its a temporary fix while I write a compatibility for CIT

**Comment by fxmorin** [comment]
Could you pass me the resource pack you are using for testing?

**Comment by fxmorin** [comment]
I haven't had the time to work on this. Although currently in v0.5.0, you can disable the custom item frame renderer, which should fix your issue

**Comment by fxmorin** [comment]
@NovaXCIV All the CIT packs I've tried don't work

**Comment by JustAHuman-xD** [comment]
make sure you are using cit resewn, cit does work perfectly in 1.19

**Comment by JustAHuman-xD** [comment]
or using optifine, cit works perfectly on both

**Comment by Agent00Ming** [comment]
*Edit to the original issue: Chime resource packs are unaffected. I have tested with default configs on 0.5.0 and 0.5.1.*

**Comment by fxmorin** [comment]
> make sure you are using cit resewn, cit does work perfectly in 1.19

Yup, I was using cit resewn. Can someone give me a pack they have actually tested with instructions on how to recreate? I've never touched cit before, plus I'm too busy to check xD

**Comment by Agent00Ming** [comment]
[https://www.curseforge.com/minecraft/texture-packs/library-9366/download/3861999](url)
This is the pack I originally had issues with and still do when turning on custom item frame renderer.

**Comment by fxmorin** [comment]
![2022-07-21_23 04 30](https://user-images.githubusercontent.com/28154542/180353934-ef6d126f-0d1d-435b-817a-eac84ed8daf7.png)
v0.6.0 shows me the custom textures just fine when using CIT Resewn with Custom Item Frame Rendering on

**Comment by fxmorin** [comment]
If I can't recreate the issues, I can't fix them

**Comment by Agent00Ming** [comment]
That's not using CIT. It's the '?' for unknown texture

**Comment by fxmorin** [comment]
> https://www.curseforge.com/minecraft/texture-packs/library-9366/download/3861999 This is the pack I originally had issues with and still do when turning on custom item frame renderer.

So how do I use it. I asked for steps to recreate

**Comment by Agent00Ming** [comment]
Look for 'enchanted book' in the creative inventory when the pack is active and it should show a bunch of different textures

**Comment by fxmorin** [comment]
![image](https://user-images.githubusercontent.com/28154542/180354643-ceafd7b9-6797-48c1-9ebb-4a01cdb72dc8.png)

**Comment by fxmorin** [comment]
yes

**Comment by fxmorin** [comment]
Might be: https://github.com/SHsuperCM/CITResewn/issues/176

**Comment by Agent00Ming** [comment]
This is how it looks on my end. What are your CIT Resewn settings?
![image](https://user-images.githubusercontent.com/107314235/180355145-9d319796-2b99-4b2b-a16c-c8a23e425d78.png)

**Comment by fxmorin** [comment]
Are you using the 1.18.2 or 1.19 version?

**Comment by Agent00Ming** [comment]
1.19
![image](https://user-images.githubusercontent.com/107314235/180355321-26e11ca2-03e8-4449-8e1e-e3e93353c101.png)

**Comment by Agent00Ming** [comment]
![image](https://user-images.githubusercontent.com/107314235/180355983-0b2dc70b-84ed-4abf-81c5-020ea7c8cf9d.png)
I only have these More Culling and CIT Resewn + dependencies

**Comment by fxmorin** [comment]
Wow so literally the same setup. Weird

**Comment by Agent00Ming** [comment]
![image](https://user-images.githubusercontent.com/107314235/180357250-9013d1cf-6477-4823-8fa8-defa20513f03.png)
```
[main/INFO]: Loading 57 mods:
	- citresewn 1.1.1+1.19
	- citresewn-defaults 1.1.1+1.19 via citresewn
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 7.0.73 via moreculling
	- conditional-mixin 0.3.0 via moreculling
	- fabric 0.58.0+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via fabric
	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
	- fabric-blockrenderlayer-v1 1.1.18+9ff28f40a9 via fabric
	- fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.2+0d55f585a9 via fabric
	- fabric-commands-v0 0.2.23+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.28+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.2.1+07df213ea9 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.1.2+a680b9b4a9 via fabric
	- fabric-dimensions-v1 2.1.28+a6d2f785a9 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.26+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
	- fabric-item-api-v1 1.5.5+35a03c43a9 via fabric
	- fabric-item-groups-v0 0.3.26+9ff28f40a9 via fabric
	- fabric-key-binding-api-v1 1.0.18+9ff28f40a9 via fabric
	- fabric-keybindings-v0 0.2.16+df3654b3a9 via fabric
	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
	- fabric-loot-api-v2 1.1.1+03a4e568a9 via fabric
	- fabric-loot-tables-v1 1.1.4+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.11+33fbc738a9 via fabric
	- fabric-models-v0 0.3.15+9ff28f40a9 via fabric
	- fabric-networking-api-v1 1.1.0+442de8b8a9 via fabric
	- fabric-networking-v0 0.3.15+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.8+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
	- fabric-registry-sync-v0 0.9.18+23c4cfefa9 via fabric
	- fabric-renderer-api-v1 1.0.8+9ff28f40a9 via fabric
	- fabric-renderer-indigo 0.6.10+5187d39fa9 via fabric
	- fabric-renderer-registries-v1 3.2.18+df3654b3a9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
	- fabric-rendering-v0 1.1.20+df3654b3a9 via fabric
	- fabric-rendering-v1 1.10.14+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.6+5f1a85e0a9 via fabric
	- fabric-screen-api-v1 1.0.24+f05effafa9 via fabric
	- fabric-screen-handler-api-v1 1.2.7+9ff28f40a9 via fabric
	- fabric-textures-v0 1.0.18+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
	- fabricloader 0.14.8
	- java 18
	- minecraft 1.19
	- modmenu 4.0.4
	- moreculling 1.19-0.6.0
```

**Comment by egeesin** [comment]
Next time opening a issue, please take a time to reproduce the bug for providing details or at least send the log file *at the beginning*. So that would be less exhausting for the developer and people who subscribed to this issue.

**Comment by fxmorin** [comment]
Haven't been able to reproduce so instead I told them how to fix it.
https://github.com/SHsuperCM/CITResewn/issues/181

**Comment by ardissaps** [comment]
I can confirm this, easier to test is put custom texture of potion and compare it the item texture with the one on frame, on frame return to vanilla potion texture.
On Inventory :
![image](https://user-images.githubusercontent.com/82106625/182075360-b2497031-786d-4a08-9412-b40bebb682a8.png)
When Dropped :
![image](https://user-images.githubusercontent.com/82106625/182075506-6d8c4095-2118-4596-ac77-d593e0a0e154.png)
When on Frame (return to vanilla), we can compare it with WTHIT displayed icon (i draw red line): 
![image](https://user-images.githubusercontent.com/82106625/182075705-a945116a-19df-495f-a092-01c2d2d640bb.png)

**Comment by FxMorin** [comment]
This has been fixed in the latest release
