### ISSUE TITLE
Game crashes a few seconds after loading a world with sodium 0.6.0-beta.1+mc1.21

### ISSUE THREAD

**Issue by JellyBubb1e** [FxMorin/MoreCulling#277]
https://mclo.gs/iRKSqMf
CaffeineMC/sodium-fabric#2278

**Comment by akbe2020** [comment]
I have the same issue 
https://mclo.gs/aU4Kgro

**Comment by GamerGuy95953** [comment]
@akbe2020 
@JellyBubb1e 

Try this, Change the leaves culling setting from whatever you had to "fast". This fixed the issue for me. There may be other leaves culling settings you can use that can fix the issue probably but I'm too lazy to try them all.

How I knew to change that setting specifically was that I saw it was throwing errors relating to leaves culling.
