### ISSUE TITLE
Minecraft crashed immediately after loading in word 

### ISSUE THREAD

**Issue by DenizUe** [FxMorin/MoreCulling#278]
I narrowed it down to this Mod, and it was working fine just a few days ago. I updated some other mods before launching the game today, so I guess another mod makes it crash with this one. The problem is I don't know which mod since I hit "update all" and didn't check which ones got updated. 

I can share all the mods I have installed if this might help in any way.

**Comment by Crackers0106** [comment]
It's this mod combined with Sodium 0.6 that causes the crash

**Comment by GamerGuy95953** [comment]
Try this, Change the leaves culling setting from whatever you had to "fast". This fixed the issue for me. There may be other leaves culling settings you can use that can fix the issue probably but I'm too lazy to try them all.

**Comment by FxMorin** [comment]
Should be fixed in 0.27.1
