### ISSUE TITLE
1.18.2

### ISSUE THREAD

**Issue by ImNotStable** [FxMorin/MoreCulling#28]
Could you add at least one version with 1.18.2 support there's a bug where it mades glass see through blocks on 0.1.4v and many mods haven't updated to 1.19. This mod gives me insane performance gains and I really want to be able to use it.

**Comment by fxmorin** [comment]
Alright fine, if I get the time I will backport only the block state culling optimizations

**Comment by ImNotStable** [comment]
I appreciate that thank you
