### ISSUE TITLE
The video settings button has no toggle

### ISSUE THREAD

**Issue by HyperSoop** [fxmorin/MoreCulling#29]
I'd like it to be able to be removed - there's not much to configure there, it may only cause confusion. Why even have it? I thought a config access point in Mod Menu was enough.

**Comment by fxmorin** [comment]
Will be in the next release. Should be v0.6.0
https://github.com/fxmorin/MoreCulling/commit/e09c3cacc4a8e2323b65d1fbc5d9f998aa098852
