### ISSUE TITLE
End Gateway and some BlockState culling are not working (earlier versions require Sodium)

### ISSUE THREAD

**Issue by yumunet** [FxMorin/MoreCulling#292]
The following 4 culls are not working in latest 0.27.1.
- End Gateway
- BlockState Culling (the following three. Maybe not all)
  - Top of fence
  - Chorus plant
  - Bamboo

Also, these culls don't work without Sodium in 0.26.0 or earlier.
"End Gateway" and "Top of fence" in 0.23.1 to 0.26.0.
"Chorus plant" and "Bamboo" after in 0.21.0 to 0.26.0.

In 0.13.0 to 0.20.3, BlockState culling doesn't work with Fabric API, but it works when Sodium is added there. (the end gateway culling is unimplemented in this version)
Since 0.21.0 or later, FabricAPI is required, so it is incompatible with the IndigoRendrer?

## Test

I have actually checked in each version.

World:
![](https://github.com/user-attachments/assets/f247cc40-7bb7-44cf-bf56-b8d7ddaf275f)

### 0.27.1
1.21.1, Fabric Loader 0.16.5 (Mods: Cloth Config 15.0.140, Fabric API 0.104.0, Mod Menu 11.0.2, Placeholder API 2.4.1)

**All four aren't culled** (even with Sodium 0.6.0 beta1 or beta2).

End Gateway:
<img src="https://github.com/user-attachments/assets/eae1d5e1-856c-4fe3-921f-f9f5ac95cc5e" width="50%">

Top of fence:
<img src="https://github.com/user-attachments/assets/f7e9bf36-1c9f-4b1c-a10b-95f5f0faf632" width="50%">
<img src="https://github.com/user-attachments/assets/5940cc20-3750-4a07-9edb-cfa2dd868cfc" width="50%">

Chorus plant:
<img src="https://github.com/user-attachments/assets/33e3b84e-bb0e-42d1-be60-b3b0734c2266" width="50%">

Bamboo:
<img src="https://github.com/user-attachments/assets/031f6735-e226-480a-8def-057809fd6067" width="50%">

### 0.26.0
1.21.1 (Same instance as above)

They don't work as it is, but **they work with Sodium 0.5.11.**

End Gateway:
<img src="https://github.com/user-attachments/assets/8a134731-cd40-49d0-85d0-a5e6881eb483" width="50%">

Top of fence:
<img src="https://github.com/user-attachments/assets/33de6221-9865-4664-ab23-9c76ccd8d545" width="50%">
<img src="https://github.com/user-attachments/assets/e45b6705-240d-4928-99cb-b854e2a613da" width="50%">

Chorus plant:
<img src="https://github.com/user-attachments/assets/d08b6094-8aa9-421d-bdff-4c5d6f450ec3" width="50%">

Bamboo:
<img src="https://github.com/user-attachments/assets/c38e584d-287c-4f2a-a6e5-c12eb0ed6a86" width="50%">

### 0.23.1
1.20.4, Fabric Loader 0.16.5 (Mods: Cloth Config 13.0.138, Fabric API 0.97.2, Mod Menu 9.2.0, Placeholder API 2.4.0 pre1)

They work with Sodium 0.5.8. (Not without Sodium)

### 0.22.1
1.20.4 (Same instance as above)

**"End Gateway" and "Top of fence" are culled without Sodium**, but "Chorus plant" and "Bamboo" culling require Sodium 0.5.8.

### 0.21.0
1.20.4 (Same instance as above)

Exactly the same as above.

### 0.20.3
1.20.4 (Same instance as above)

(The "End Gateway" culling isn't yet implemented in this version.
Also, top of fence with flower pots on top isn't culled, but that is fixed in [0.21.0](https://github.com/FxMorin/MoreCulling/issues/154#issuecomment-1880885041).)

"Top of fence" (with pressure plate) and "Chorus plant" and "Bamboo" **aren't culled because of the Fabric API, but they are culled when Sodium 0.5.8 is added there.**

They also work without the Fabric API.
By the way, they work without the Fabric API and with Sodium 0.5.8.

### 0.13.0
1.19.3, Fabric Loader 0.16.5 (Mods: Cloth Config 9.1.104, Fabric API 0.76.1)

Exactly the same as above. (Sodium 0.4.9)

### 0.12.5
1.19.3 (Same instance as above)

They work with Fabric API. (Even with Sodium)

**Comment by FxMorin** [comment]
Wow, thanks. This should help a lot once I find time, or maybe @1foxy2 can look at it.
