### ISSUE TITLE
End Rod culling is not working

### ISSUE THREAD

**Issue by yumunet** [FxMorin/MoreCulling#294]
The top of end rod isn't culled. (0.23.1 or later)
Unlike #292, it doesn't work with Sodium. However, like the top of the fence culling, this happens in 0.23.1 or later, so it may be related.

## Tests

World:
![](https://github.com/user-attachments/assets/4c7e16a6-e362-4c6f-9d3b-a471884b4d5d)

### 0.27.1
1.21.1, Fabric Loader 0.16.5 (Mods: Cloth Config 15.0.140, Fabric API 0.104.0)

It doesn't work (even with Sodium 0.6.0 beta1 or beta2).
<img src="https://github.com/user-attachments/assets/0f1d26e9-47ef-40e7-aae8-37018af0149a" width="50%">
<img src="https://github.com/user-attachments/assets/5feb54b7-e56d-40eb-961b-2646df39a63e" width="50%">

### 0.23.1
1.20.4, Fabric Loader 0.16.5 (Mods: Cloth Config 13.0.138, Fabric API 0.97.2)

It doesn't work (even with Sodium 0.5.8).

### 0.22.1
1.20.4 (Same instance as above)

It works.
<img src="https://github.com/user-attachments/assets/41fe4710-f7e3-4f34-825c-364d8b7d7c15" width="50%">
<img src="https://github.com/user-attachments/assets/69f2a5f6-71f2-43e6-b79d-4795a85e3775" width="50%">

**Comment by yumunet** [comment]
PS:
Sorry for submitting so many issues.
I found these issues while testing the effect of More Culling.

I know you are busy, so I don't mean to rush you.👍️

**Comment by FxMorin** [comment]
@yumunet All good. We are working on fixing a lot of the issues and releasing a multiloader version.
So this is actually pretty good timing

**Comment by yumunet** [comment]
Sorry, this is not fixed in v1.0.0-beta.1. (Both Fabric and NeoForge 21.1.61)
