### ISSUE TITLE
Elytraslot crashes on neoforge due to mismatched mixinsquared versions

### ISSUE THREAD

**Issue by VaporeonScripts** [FxMorin/MoreCulling#297]
1.21.1
https://mclo.gs/Z3ZAKNt

**Comment by VaporeonScripts** [comment]
So I have to report it to elytra slot owner?

**Comment by 1foxy2** [comment]
yes

**Comment by VaporeonScripts** [comment]
same issue happens with chunksending mod bruh

**Comment by FxMorin** [comment]
We are working on a fix

**Comment by VaporeonScripts** [comment]
alright

**Comment by VaporeonScripts** [comment]
the issue with elytra slot is solved, but now additional lantern does the same :skull:

**Comment by Bawnorton** [comment]
I aim to fix this inside mixinsquared itself, when loading jij'd jars I assumed that neo would only load the latest, like fabric, but it doesn't, it tries to load all versions and causes a resolution exception when multiple versions are loaded which is a right pain in the arse.

**Comment by 1foxy2** [comment]
neo does load only the latest version. the problem is what Jij identifies jars by group and name given in jarjar parameters. the group of mixinssquared changed so neo thinks its a different mod

**Comment by Bawnorton** [comment]
group never changed. Maven changed when migrating from jitpack but the group has always been the same

**Comment by 1foxy2** [comment]
it was com.github.bawnorton. now its com.bawnorton
![image](https://github.com/user-attachments/assets/e0272c66-5f01-450a-8719-80ca6642cca1)

**Comment by Bawnorton** [comment]
yeah the maven changed but the metadata inside the jar has always been `com.github.Bawnorton`
<img width="963" alt="Screenshot 2024-09-30 at 10 02 41 AM" src="https://github.com/user-attachments/assets/717bf11b-77a7-4042-a1d0-c3eccd8bd56e">
<img width="934" alt="Screenshot 2024-09-30 at 10 02 52 AM" src="https://github.com/user-attachments/assets/f7314bcb-2c36-4766-a7a4-5c64c738f4e9">

**Comment by Bawnorton** [comment]
Ah I see, nvm, The jij pulls from the maven group. Frick
