### ISSUE TITLE
About powder snow culling

### ISSUE THREAD

**Issue by yumunet** [FxMorin/MoreCulling#298]
The on/off option for powder snow culling was removed in v1.0.0-beta.1, but powder snow culling is working.
And like #165, the gray texture on the top of the grass block is visible.
This is disabled when "BlockState Culling" is turned off.
![](https://github.com/user-attachments/assets/d0fd52d8-2f5d-46e4-9f2f-44c96fcfeb08)

Are these the intended behaviors?

**Comment by FxMorin** [comment]
Pretty sure this is caused by sodium

**Comment by yumunet** [comment]
I tested without Sodium (1.21.1, Fabric 0.16.5, Cloth Config 15.0.140, Fabric API 0.105.0, More Culling 1.0.0-beta.1) and it occurs.
![](https://github.com/user-attachments/assets/b561fb4b-ab7b-45ce-a9ed-68f437dd2d63)

**Comment by FxMorin** [comment]
Ehhh, and it doesn't happen in vanilla, right?
I have no idea how thats possible. Since we removed the mixins

**Comment by yumunet** [comment]
Yes, it doesn't happen in vanilla...
![](https://github.com/user-attachments/assets/2425cf40-66c3-42c2-8589-fcd3233b815c)

This doesn't happen when BlockState Culling is turned off, so maybe BlockState Culling is related?

**Comment by FxMorin** [comment]
Wow weird
