### ISSUE TITLE
The top of a block undeneath bamboo is culled

### ISSUE THREAD

**Issue by Hippopipo** [FxMorin/MoreCulling#301]
![2024-10-03_13 40 36](https://github.com/user-attachments/assets/d152d304-85fe-4682-a921-88d15ff2328e)
Updated my modpack to 1.21.1 from 1.21 and noticed this. Fixed when blockstate culling is disabled. 
Mod version: 1.0.0-beta.2
Loader: Fabric

**Comment by Hippopipo** [comment]
Forgot to upload logs
https://mclo.gs/jfNeYF3

**Comment by FxMorin** [comment]
@1foxy2 Ya this is what I thought might happen.

**Comment by Hippopipo** [comment]
Hey, i found out what is causing this. It's [Client tweaks](https://modrinth.com/mod/client-tweaks/versions), and its setting to expand glass pane hitboxes.
