### ISSUE TITLE
Failure when trying to open the Sodium Options menu

### ISSUE THREAD

**Issue by Tapacywka** [FxMorin/MoreCulling#310]
What caused the crash?
https://modrinth.com/mod/sodium-options-api

Logs with visible issue:
https://mclo.gs/hZcFdWU

Modpack for testing (latest NeoForge 1.21.1 build):
https://modrinth.com/modpack/forgified-core

A more detailed description of the problem:
If the Sodium Options API mod is installed, the game crashes when trying to open the Sodium Options menu.
If you use the option `enableSodiumMenu = false`, the Sodium Options menu opens normally.

**Comment by 1foxy2** [comment]
it crashes because moreculling logo has capital letters in its name. i think you should report this to sodium options api
