### ISSUE TITLE
[Feature] Support for VulkanMod's chunk builder

### ISSUE THREAD

**Issue by NXTler** [FxMorin/MoreCulling#312]
Greetings,
I'm a none code contributor of VulkanMod, which implemented a custom chunk builder by version 0.4.0 which sadly caused More Culling to have no effect anymore. To be compatible again, More Culling would need to inject the chunk builder code, similar to have many mods do it for Sodium.
I do understand that requesting a fix for something VulkanMod broke is kind of rude, but it's unfortunately the only feasible solution from all I know. I'm not a developer and only have a weak understanding of VulkanMod's code, so if any questions arise, you will need to talk to Collateral.

**Comment by 1foxy2** [comment]
added mixin to make blockstate culling work with vulkan. reopen the issue if there is something else what doesn't work

**Comment by NXTler** [comment]
Thanks a lot, the community will appreciate your effort!
