### ISSUE TITLE
1.21.3: "BlockState Culling" "on", makes glass "see-though" 

### ISSUE THREAD

**Issue by isvein** [FxMorin/MoreCulling#318]
Hello :)
With "BlockState Culling" turned on, glass becomes "see-though"  on sides that are next to solid blocks.

Is this a bug or a feature?

With this mod in 1.19.4, this did not happen

**Comment by isvein** [comment]
![2024-11-29_13 51 53](https://github.com/user-attachments/assets/403d6474-806f-44fd-b834-da5ec63b9634)

I even tried to disable all other mods and just this one, same happens.

**Comment by isvein** [comment]
I tested some more, to see what happened if I removed my texture pack, and it does not happen with default texture.
It happens with this setting "on" and "BDCraft" texture pack at the same time.

Possible that you can test this combo too?

**Comment by isvein** [comment]
Only difference is I use the 256x version :O 
Now Im more confused, but thanks :)

**Comment by 1foxy2** [comment]
![image](https://github.com/user-attachments/assets/d67dddec-b0b9-4244-b611-79c23333d4ad)
it seems to happen only with 256x version. i will look in to it once i finish poritng to 1.21.4, you can add glass to the dont cull list for now
