### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.NullPointerException: Cannot read field "modCompatibility" because "ca.fxco.moreculling.MoreCulling.CONFIG" is null

### ISSUE THREAD

**Issue by Thunderrock424242** [FxMorin/MoreCulling#324]
[latest.log](https://github.com/user-attachments/files/18133865/latest.log)

**Comment by 1foxy2** [comment]
can you provide minimum amount of mods to reproduce this error?

**Comment by Thunderrock424242** [comment]
I updated my mods and now I can't reproduce. In the log there's a mod list to reproduce
