### ISSUE TITLE
Marked as FpsReducer1.12.2-1.15 Mod

### ISSUE THREAD

**Issue by PunchmadeDav** [FxMorin/MoreCulling#327]
version: https://modrinth.com/mod/moreculling/version/0.24.0
mc version: 1.20.1
Just make a curseforge instance and add moreculling. It will say that it is FPSReducer instead. making curseforge modpacks download fpsreducer instead of using moreculling

**Comment by 1foxy2** [comment]
i can add 0.24.0 to curseforge but not sure if its gonna fix it

**Comment by PunchmadeDav** [comment]
this did fix it actually. thank you
