### ISSUE TITLE
Confusing sliders

### ISSUE THREAD

**Issue by Navota** [fxmorin/MoreCulling#35]
Maybe i'm not aware of something but the sliders for the lod and 3 face culling are up to 768 and 48 respectively. Shouldnt they be the same as the block distance, 0-256 and 0-16? You might want to elaborate in the tooltip if this is your intended behaviour, because this might confuse some people, me included.

**Comment by fxmorin** [comment]
I did want to make it blocks although that would limit how much you can configure it. I wanted to give the player as much control over the values as possible and the game calculates the distance as 3 = 1 block. So it's smarter to do it that way.
I may change that later tho
