### ISSUE TITLE
Bamboos, End Rods, Glass Panes aren't fully culled. (Not so sure of why)

### ISSUE THREAD

**Issue by NaiNonTH** [fxmorin/MoreCulling#38]
Here are some screenshots of the issue.

![2022-07-18_21 47 02](https://user-images.githubusercontent.com/61338902/179538199-7fa51272-25eb-4107-9d02-1437026cdbde.png)

![2022-07-18_21 47 10](https://user-images.githubusercontent.com/61338902/179538219-52ee17f8-2afa-431f-a4e0-f2292e765428.png)

**Comment by NaiNonTH** [comment]
Okay, it isn't.

And there's more; Glass panes and End rods are also not culled.

**Comment by NaiNonTH** [comment]
Thankfully, it still works with fences.

**Comment by fxmorin** [comment]
It's `lambdabettergrass`, I am currently working on that. It will be fixed next version

**Comment by fxmorin** [comment]
> Thanks a ton. However, the glass panes culling isn't working, but I think that's a Continuity issue, yet it still can be fixed.

Same thing, it's already fixed in the next release. Should come out today
