### ISSUE TITLE
Backport CullLessLeaves compatibility to 1.18.2

### ISSUE THREAD

**Issue by WubTheGame** [fxmorin/MoreCulling#39]
I'd like to use these mods together, but the compatibility between the two mods seems exclusive to 1.19. Would you mind at least getting that into 1.18 please? Thanks in advance.

**Comment by fxmorin** [comment]
That would need to be done for both MoreCulling and CullLessLeaves. I'm currently too busy to do that

**Comment by fxmorin** [comment]
New 1.18.x branch will fix this issue. Although CullLessLeaves will have to also backport the compatibility

**Comment by WubTheGame** [comment]
Oh, thank you so much.
