### ISSUE TITLE
v0.6.0-pre1 crashes without Sodium

### ISSUE THREAD

**Issue by ardissaps** [fxmorin/MoreCulling#42]
https://paste.atlauncher.com/view/a7289b7d-cf84-4b3b-9e14-86dbfbb5892a

**Comment by fxmorin** [comment]
Thanks for reporting it. It will be fixed by v0.6.0

**Comment by ardissaps** [comment]
That log is from my instance that are using Vulkan renderer, not Sodium. But the the update also fixed the Vulkan, tested today. Thanks.

**Comment by fxmorin** [comment]
Yup, your welcome
