### ISSUE TITLE
Leaves always get culled as if the culling option is at FAST whenever fancy leaves are used on fast graphics.

### ISSUE THREAD

**Issue by HyperSoop** [fxmorin/MoreCulling#45]
Sodium has an option to enable fancy leaves without switching to fancy graphics. In that scenario, MoreCulling 0.6.0+ acts as if the leaves culling mode is at Fast all the time.

**Comment by fxmorin** [comment]
Alright thanks ill try to fix it for the next release

**Comment by fxmorin** [comment]
Fixed in the next release (and current dev state)
