### ISSUE TITLE
Mangrove roots don't get affected by leaves culling.

### ISSUE THREAD

**Issue by HyperSoop** [fxmorin/MoreCulling#46]
Well it's obvious they are not, but those are blocks of simular kind so maybe have an option to apply leaves culling to roots too.

**Comment by fxmorin** [comment]
Shouldn't be hard to do, ill check. Not sure if I want to batch it together or not tho.
Vanilla has a weird culling check for roots

**Comment by fxmorin** [comment]
So it seems that in vanilla. Mangrove roots cull there top and bottom faces if next to more mangrove roots. Although no other faces are culled. I'll add an option to include them

**Comment by fxmorin** [comment]
Mangrove Roots support in: https://github.com/fxmorin/MoreCulling/commit/4c5786b226a59b8bd31faac5ebe026716b07e036
Will be included in the next release

**Comment by Minecrafthyr** [comment]
@FxMorin So, this breaks vanilla top and bottom culling next to mangrove roots forever? I think vanilla is more realistic. Could you add it back?

**Comment by FxMorin** [comment]
Theres a config option to disable mangrove root culling
