### ISSUE TITLE
Suggestion: Feature for Culling Powder Snow Against Solid Blocks

### ISSUE THREAD

**Issue by Fourbo** [fxmorin/MoreCulling#48]
I spent sometime looking through the Java edition bug tracker, and I found one culling issue left open I wanted to leave as a suggestion if you wanted to implement it.
The bug linked here seems to note that the faces of powder snow are only culled against other powder snow blocks, and not against solid blocks. I'm not very familiar with how culling works, but I thought that a fix for this might result in a slight performance increase in areas with lots of powder snow.
https://bugs.mojang.com/browse/MC-220488?jql=project%20%3D%20MC%20AND%20status%20%3D%20Open%20AND%20text%20~%20culling%20ORDER%20BY%20affectedVersion%20DESC

**Comment by fxmorin** [comment]
Will be in v0.6.1
