### ISSUE TITLE
Leaves get culled when behind a transparent block

### ISSUE THREAD

**Issue by HappyCord** [fxmorin/MoreCulling#49]
only happens on fast and depth mode

for example:
this leave is getting culled when behind this moss carpet
![2022-07-22_11 39 42](https://user-images.githubusercontent.com/66735773/180475677-3a16b719-52ca-4f41-ae34-180f53f48b4e.png)
![2022-07-22_11 40 05](https://user-images.githubusercontent.com/66735773/180475865-e74f7f7b-662e-4061-88be-afc4b48e05fa.png)

**Comment by fxmorin** [comment]
Good to know, should be fixed in the next release

**Comment by Funtimes909** [comment]
Was also having this issue lmao
