### ISSUE TITLE
Leaves cull settings dont do anything.

### ISSUE THREAD

**Issue by TheRealJake12** [fxmorin/MoreCulling#50]
I want them to function like CLL and setting it to Depth and 2, makes them ugly
![2022-07-24_12 45 06](https://user-images.githubusercontent.com/84357907/180659513-fa6e36a3-cf68-481f-939c-49187670f99c.png)
nothing works with the latest update

**Comment by fxmorin** [comment]
This should be fixed in v0.6.1, can you please test that. Thanks

**Comment by TheRealJake12** [comment]
it has. Thanks. we can close :)
