### ISSUE TITLE
Leaves Culling still actives where it shouldn't with specific resource packs on servers

### ISSUE THREAD

**Issue by NaiNonTH** [fxmorin/MoreCulling#56]
I use the Fancy leaves option (transparent leaves) with a Bushy Leaves for Faithful 32x, which I made, and a resource pack which I'm developing and it shows some kind of like an x-ray effect behind leaves blocks because those faces are hidden, giving such odd-looking as this screenshot provides—looks more obvious with leaves blocks on the floor.

![2022-07-28_22 43 43](https://user-images.githubusercontent.com/61338902/181583154-ff25f2c1-7130-413d-a8a5-49f085aa79de.png)

It seems like it only happens on servers, and I'm not sure why this happens, but I think it's because of the modeling method that I'm using with those resource packs. If you don't mind, can you take a look at the code?
**Sample:** [Bushy Leaves for Faithful 32x V1.1.zip](https://github.com/fxmorin/MoreCulling/files/9212313/Bushy.Leaves.for.Faithful.32x.V1.1.zip)

**Comment by fxmorin** [comment]
Ah good. This is because its now a multipart baked model.
Thanks for reporting this, currently multipart block models that are transparent are not supported. Although this will help me make them supported.

There's a couple things about Multiparts that make them hard to handle currently.
Firstly multiparts can be based on the blockstate, which my system does not currently account for. Also if one part of the multipart is considered transparent I need to consider all parts transparent.

I thought my system would work with multiparts correctly due to them never being used directly although this obviously proves im wrong.

I will work on including blockstates with the system directly. It's something on my todo list anyways since its going to increase performance for blocks that have multiple block states where some are transparent

**Comment by fxmorin** [comment]
This has now been fixed internally, although I want to rewrite a good portion of how warped/container models are handled in order to bring much more performance while not limited the checks

**Comment by fxmorin** [comment]
Fixed in Dev branch, expect this to be fixed when v0.8.0 comes out.
Although it would be nice if you could test this version also: https://github.com/fxmorin/MoreCulling/suites/7568491709/artifacts/312834638

**Comment by NaiNonTH** [comment]
Your dev branch fixes this issue. Thanks. :)

**Comment by NaiNonTH** [comment]
Anyway, from this issue, I think it would be a pretty good idea to add a force culling for those who like using opaque leaves, which doesn't affect the look of the overall trees while gaining a significant performance improvement for fast leaves.

**Comment by fxmorin** [comment]
It already is forced ;)
If you are using fast rendering, I cull the leaves with fast.

**Comment by NaiNonTH** [comment]
Oh, lol

**Comment by NaiNonTH** [comment]
Ah well, I mean to cull the _other_ block faces that are facing the leaves.

**Comment by NaiNonTH** [comment]
Well, the "Force Leaves Culling" I meant is that block faces behind the leaves will also be hidden as well. I think that would improve such performance.

**Comment by fxmorin** [comment]
> Well, the "Force Leaves Culling" I meant is that block faces behind the leaves will also be hidden as well. I think that would improve such performance.

When leaves are opaque, all block faces for leaves are culled, I believe this is the force culling you are talking about.

> Ah well, I mean to cull the other block faces that are facing the leaves.

Oh thats actually a really good idea. That's right, leaves are considered not opaque and possibly transparent so blocks behind it are not culled. Ok I can definitely add that to the mod, thanks

**Comment by fxmorin** [comment]
Currently:  
![2022-07-29_12 04 41](https://user-images.githubusercontent.com/28154542/181802759-0022edb0-1424-4fdc-8fda-41f5843433f5.png)
![2022-07-29_12 04 45](https://user-images.githubusercontent.com/28154542/181802762-345f5ed3-d12d-4a77-af65-580baf7e25f6.png)
What the next version will do:  
![2022-07-29_12 22 11](https://user-images.githubusercontent.com/28154542/181802886-0cd0b1cf-54d5-4036-8124-7ffb82b7d208.png)
![2022-07-29_12 23 04](https://user-images.githubusercontent.com/28154542/181802892-8eb58ddc-7027-4f1c-910e-e679bd68642e.png)

Really good suggestion, thanks

**Comment by NaiNonTH** [comment]
Nice! Thank you so much, anyway. :D
