### ISSUE TITLE
[1.19.1] Crash on Startup

### ISSUE THREAD

**Issue by pewblaze** [fxmorin/MoreCulling#59]
Im not sure what happens here. But more culling is written in the file ^^"

moreculling-1.19.1-0.8.0
fabric-api-0.58.5+1.19.1
Fabric 1.19.1 -> Loader 0.14.8
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000019415733046, pid=15216, tid=7500
#
# JRE version: OpenJDK Runtime Environment Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-32931 (17.0.3+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# J 23482 c2 ca.fxco.moreculling.utils.SpriteUtils.getOpacity(Lnet/minecraft/class_1011;II)B (51 bytes) @ 0x0000019415733046 [0x0000019415733000+0x0000000000000046]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
#
```
Its not the whole file, but there are a few private infos i guess ^^"
[latest.log](https://github.com/fxmorin/MoreCulling/files/9227780/latest.log)

EDIT:
Sorry idk why its so big D:

**Comment by fxmorin** [comment]
That log has nothing in it to help

**Comment by fxmorin** [comment]
Can you try redownloading the mod and trying again?

**Comment by Footage2-Amply-Pounce** [comment]
I'm having the same issue. Thought my RAM was faulty at first, but then noticed that the log specifically mentions MoreCulling and removing the mod let the game run. The issue only happens with v0.8.0, v0.7.0 works without problems.

https://gist.github.com/Footage2-Amply-Pounce/8028aa617c46ebc5bbbf5bd56c1a36eb

**Comment by fxmorin** [comment]
Humm alright thanks for sharing that
