### ISSUE TITLE
Mods that prevent MoreCulling from working

### ISSUE THREAD

**Issue by fxmorin** [fxmorin/MoreCulling#6]
This issue will be used as a list of mods that currently don't support MoreCulling so that I can go through the mods and fix the issues.

### Supported Rendering Engines
- Vanilla
- [Fabric-Api](https://github.com/FabricMC/fabric/tree/1.19/fabric-renderer-indigo) (Indigo)
- [Sodium](https://github.com/CaffeineMC/sodium-fabric) (sodium) Added in v0.1.4
- [Indium](https://github.com/comp500/Indium)

### Currently Unsupported Mods
- [LambdaBetterGrass](https://github.com/LambdAurora/LambdaBetterGrass) (Wont crash - Some optimizations still work)

### Currently Unsupported Rendering Engines
- None

### Rendering Engines that need testing
- [FREX](https://github.com/vram-guild/frex) (pastal)
- [Canvas](https://github.com/vram-guild/canvas) (pastal + canvas)
- [VulkanMod](https://github.com/xCollateral/VulkanMod)
- [Iris](https://github.com/IrisShaders/Iris)
- [Blaze4D](https://github.com/KilnGraphics/Blaze4D)

### Mods that need testing
- [BlocksToParts](https://github.com/Juuxel/BlocksToParts)
- [connected-block-textures](https://github.com/TwilightFlower/connected-block-textures)

I will put putting all this info into a wiki page before the official release of the mod. *Once this is no longer an Alpha build*

---

If you want to test if the mod is working, an easy way to do this is by using a chorus plant, and testing [this bug](https://bugs.mojang.com/browse/MC-249693)
There might be an automated system in the future, although don't get your hopes up

**Comment by ardissaps** [comment]
so basicaly i should remove this mod if i have sodium?

**Comment by ardissaps** [comment]
so basicaly i should remove this mod if i have sodium?

**Comment by fxmorin** [comment]
It shouldn't do anything if you have sodium, so yes. I'm currently fixing that

**Comment by ardissaps** [comment]
> It shouldn't do anything if you have sodium, so yes. I'm currently fixing that

Is this different from Sodium builtin culling also from below mod ?
https://modrinth.com/mod/entityculling

**Comment by fxmorin** [comment]
Blockstate culling, not at all related to entity culling or sodium culling

**Comment by ardissaps** [comment]
> Blockstate culling, not at all related to entity culling or sodium culling

How about Cull Leaves?

**Comment by fxmorin** [comment]
No, only blocks that have non-full block hitboxes are currently affected. No mod exists that does this like mine currently

**Comment by Scarlaid** [comment]
Running with Continuity fine here 😁

**Comment by Scarlaid** [comment]
what about this mod? - [CullLessLeaves](https://www.curseforge.com/minecraft/mc-mods/cull-less-leaves)

**Comment by fxmorin** [comment]
> Running with Continuity fine here 😁

Does it pass the chorus plant test?

**Comment by Scarlaid** [comment]
> > Running with Continuity fine here 😁
> 
> Does it pass the chorus plant test?

Been playing on a server a while with Continuity, no crashing
Going back to singleplayer creative world to recheck if it spamming the log while looking at Chorus Plant, dont seem to see it, and no crashing

![image](https://user-images.githubusercontent.com/90851437/172011703-20d9f135-cde6-49cc-8db5-f0e02e098dfe.png)
![huge_2022-06-04_22 21 54](https://user-images.githubusercontent.com/90851437/172011864-f8e0a7ff-bc92-4ce8-a204-8a7f0bf7bf5c.png)

**Comment by fxmorin** [comment]
@Scarlaid I meant this bug https://bugs.mojang.com/browse/MC-249693 that I linked in the issue. I need to know if continuity just overrides it or not if the chorus internals are culled then it works.

**Comment by NaiNonTH** [comment]
@fxmorin Cull Less Leaves mod also prevents from Moreculling mod from working.

**Comment by NaiNonTH** [comment]
It works with Sodium for me, which idk why, but it doesn't work with CullLessLeaves mod.

But hey, at least it still works with Cull Leaves.

**Comment by NaiNonTH** [comment]
> It works with Sodium for me, which idk why, but it doesn't work with CullLessLeaves mod.
> 
> But hey, at least it still works with Cull Leaves.

Also, still works with continuity for me.

**Comment by isXander** [comment]
Sodium has a BlockOcclusionCache (see CullLessLeaves for integration)

**Comment by fxmorin** [comment]
@isXander It's already patched, just not in a release

**Comment by FwuffyPetsOwO** [comment]
@fxmorin Version 0.2.0 on 1.19 properly culls all affected blocks when used with Continuity. I used spectator mode to confirm.

**Comment by fxmorin** [comment]
cool thanks

**Comment by RaptaG** [comment]
FREX seems to work:
![2022-06-16_15 29 29](https://user-images.githubusercontent.com/77157639/174070019-87763ca5-372f-42ff-a317-0253d45d16c3.png)
Crashlog: https://mclo.gs/BfWvcab

**Comment by fxmorin** [comment]
@RaptaG I need you to actually go into the chorus fruit. That image tells me nothing, also what's that crashlog?

**Comment by RaptaG** [comment]
> @RaptaG I need you to actually go into the chorus fruit. That image tells me nothing, also what's that crashlog?

Ok, I'll do that. The crashlog is for you if you wanted to check anything there.

**Comment by barackenkumpel** [comment]
Chorus plant culling works for me with Iris and Indium.

**Comment by RaptaG** [comment]
Does LBG still causes problems?

**Comment by RaptaG** [comment]
The description is outdated..

**Comment by fxmorin** [comment]
Due to the mod no longer being Alpha. I have moved it into its own discussion.
https://github.com/fxmorin/MoreCulling/discussions/31#discussion-4209006
