### ISSUE TITLE
Incompatible with DashLoader

### ISSUE THREAD

**Issue by PweSol** [fxmorin/MoreCulling#65]
MoreCulling makes DashLoader [(CurseForge)](https://www.curseforge.com/minecraft/mc-mods/dashloader) [(GitHub)](https://github.com/TeamQuantumFusion/DashLoader) re-cache each time on startup. This breaks the purpose of DashLoader, which _"accelerates the Minecraft Asset Loading system by caching all of its content, This leads to a much faster game load"_.

**Comment by fxmorin** [comment]
A decent amount is already fixed. Although the `getModels` is part of the API. So either I change the API method or they change there accessor name, which is easier

**Comment by fxmorin** [comment]
Fixed in dashloader

**Comment by PweSol** [comment]
there still seem to be some issues https://github.com/TeamQuantumFusion/DashLoader/pull/25#issuecomment-1201505842
