### ISSUE TITLE
Chorus flower invisible end stone

### ISSUE THREAD

**Issue by Brottweiler** [fxmorin/MoreCulling#68]
The end stone block under chorus flower becomes invisible.
![image](https://user-images.githubusercontent.com/1613137/182228413-bb51ef86-02d8-4069-9ff7-ebbe1c05d328.png)

**Comment by fxmorin** [comment]
Lmao, thanks for pointing that out.
This happens cause the culling Chorus Flower has a `VoxelShapes.fullCube()` culling face since one was not set by Mojang.
I guess ill have to make one and set the cull face correctly
