### ISSUE TITLE
Crash with Cloth Config V8

### ISSUE THREAD

**Issue by ElysiaSakura** [fxmorin/MoreCulling#69]
Updated to 1.19.1, and downloaded the latest Cloth Config (V8) alongside the latest release of More Culling but using the latest cloth config causes a crash. Logs attached below:

![quilt crash](https://user-images.githubusercontent.com/8280984/182378596-7bbbd0c4-c0be-4c72-8071-37eaafc8bb79.png)
[crash-08-02-2020.log](https://github.com/fxmorin/MoreCulling/files/9242297/crash-08-02-2020.log)

**Comment by fxmorin** [comment]
This is fixed in v0.9.0
