### ISSUE TITLE
Cull Less Leaves mod crashes

### ISSUE THREAD

**Issue by fxmorin** [fxmorin/MoreCulling#7]
> @fxmorin Cull Less Leaves mod also prevents from Moreculling mod from working.
> (Even makes the game unexpectedly crashed)

_Originally posted by @NaiNonTH in https://github.com/fxmorin/MoreCulling/issues/6#issuecomment-1146642291_

**Comment by NaiNonTH** [comment]
Thanks for reposting this :). I deleted that one because I saw this comment #https://github.com/fxmorin/MoreCulling/issues/6#issuecomment-1146625257

**Comment by fxmorin** [comment]
I will soon have an api to fix this issue

**Comment by fxmorin** [comment]
Fixed with: https://github.com/isXander/CullLessLeaves/commit/55112fc3a8abbb6f267682fd74723e6b29c574d3
Now we only need to wait for Xander to release it

**Comment by RaptaG** [comment]
O.O

**Comment by isXander** [comment]
Released
