### ISSUE TITLE
Rendering issue with create tracks

### ISSUE THREAD

**Issue by FluffyBumblebees** [fxmorin/MoreCulling#70]
All details specified in https://github.com/Fabricators-of-Create/Create/issues/479

**Comment by FluffyBumblebees** [comment]
![image](https://user-images.githubusercontent.com/60066663/182867008-fcbd7721-8c77-4be0-9b2b-ba4148790b23.png)

**Comment by fxmorin** [comment]
Can disable create from the mod now in v0.10.0

**Comment by Skidamek** [comment]
It doesnt fix the issue when create is 1.18.2 and moreculling 0.10.0 is 1.19

**Comment by fxmorin** [comment]
I don't really support 1.18.2 at the moment
