### ISSUE TITLE
backport for 1 17 1 in the future

### ISSUE THREAD

**Issue by MiFliK** [fxmorin/MoreCulling#72]
Why 1.17.1 is still important
This is the latest version with the old generation of the world

According to my tests, this is the most stable version of minecraft of all with a bunch of sodium and other mods
Starting from 1.18 there are strange fps drops and memory leaks

If this mod was on 1.17.1 it would be amazing
Since only on 1.17.1 you can play 32 chunks and above on not the most powerful PCs, while on 1.19.1
prolags and high memory usage begin

on 1.17.1 there is not one mod that optimizes bamboo
because of this, I and others have a lot of lag in the jungle

Many just love the old world generation and good performance

**Comment by fxmorin** [comment]
I'll think about it.

On the other hand...
> Starting from 1.18 there are strange fps drops and memory leaks

Do you know what causes the memory leak. Would be great to fix those in MemoryLeakFix

**Comment by MiFliK** [comment]
> Я подумаю об этом.
> 
> С другой стороны...
> 
> > Начиная с 1.18 странные падения фпс и утечки памяти
> 
> Знаете ли вы, что вызывает утечку памяти. Было бы здорово исправить их в MemoryLeakFix.

all i found out
Playing when loading chunks on a large render at least 32 chunks
Starts downloading in 10 minutes
The game starts to consume no longer 1000 - 2000 mb
And already 3000 - 4000
Rarely brushing up to 1400 and then clogging again
According to my notes, this parameter has deteriorated since version 1 18 2
On 1 17 1 everything is more or less normal
