### ISSUE TITLE
Incompatibility with Supplementaries (Hanging Signs)

### ISSUE THREAD

**Issue by Sheep7798** [fxmorin/MoreCulling#78]
I discovered this issue on supplementaries 1.19.2-2.0.13, Moonlight Lib 1.19-2.0.15 and More Culling 0.9.1.
When placing a hanging sign in the world, there is a glitched texture around it (see screenshot), and in the logs it says : 
https://pastebin.com/AU3Q7pNs

![2022-08-12_16 33 26](https://user-images.githubusercontent.com/106376800/184377488-faaac00d-8533-4320-90b3-99ea85a5cf6a.png)

After a bit of testing, I realized that the issue only happens on version 0.8.1 and higher. Here is a screenshot of it working on 0.8.0: 
![2022-08-12_16 36 41](https://user-images.githubusercontent.com/106376800/184378020-06fcb476-a50f-4d00-b68c-af55c0a0a463.png)

**Comment by fxmorin** [comment]
Is this fixed in v0.9.2?
