### ISSUE TITLE
Sodium Crash - Crash upon launching on v0.1.3

### ISSUE THREAD

**Issue by NaiNonTH** [fxmorin/MoreCulling#8]
Even without CullLessLeaves mod, the game still proceeded to crash, due to:
```
Mixin transformation of me.jellysquid.mods.sodium.client.render.occlusion.BlockOcclusionCache failed.
```
and
```
* **org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method useMoreCulling(Lnet/minecraft/class_2680;Lnet/minecraft/class_1922;Lnet/minecraft/class_2338;Lnet/minecraft/class_2350;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_2338$class_2339;)V in moreculling.mixins.json:compat.BlockOcclusionCache_sodiumMixin from mod moreculling failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap moreculling-refmap.json**
```

Log:
[latest.log](https://github.com/fxmorin/MoreCulling/files/8839187/latest.log)

No Crash Report

**Comment by NaiNonTH** [comment]
Overall, the issue was caused by BlockOcclusionCache from Sodium, which you've already mentioned that you'd already patched.

**Comment by Cccc-owo** [comment]
According to #10, with More Culling, Memory Leak Fix and Sodium on, the game will crash.
This is my log and the game only have these mods :
![image](https://user-images.githubusercontent.com/47687154/172055704-484111a4-0a7a-4559-9422-8174e29ecfd1.png)

**Comment by fxmorin** [comment]
Ya I need to look into it although im too busy to do that today. Seems sodium crashes, even though it works fine in my development enviroment

**Comment by fxmorin** [comment]
Please try v0.1.4 and tell me if you still get the same issue

**Comment by NaiNonTH** [comment]
@fxmorin Issue fixed. Thanks
