### ISSUE TITLE
Cull issue

### ISSUE THREAD

**Issue by AnomalousDeity** [fxmorin/MoreCulling#83]
when leaves are against a wall or mountain you can see through it 
![2022-08-16_12 43 15](https://user-images.githubusercontent.com/91780401/184970170-bcd7c399-cec4-44a9-966c-17392f77cf3d.png)

**Comment by fxmorin** [comment]
What texture pack & mods are you using?

**Comment by AnomalousDeity** [comment]
texture pack wise should only effect selective things such as 3d crops, 3d sun and moon, better glow berries, better vines. otherwise everything else is vanilla. 
Mods however im using quite a Bit, but world gen mods are oh the biomes you'll go, Promanade, JJthunder hills, better nether,better end and few structure mods such as When dungeons arise, better villages, explore the world.
in total im using 231 mods. 

this occurs with vanilla leaves/blocks as well, whenever its placed on the floor or side of the wall i can see though it

**Comment by fxmorin** [comment]
What are your render settings.... wait your on 1.18.2?

**Comment by AnomalousDeity** [comment]
im on 1.19 and my render settings for Cull leaves is default, render distance is 15, 30 for screenshots
leaves quality is fast, clouds are fast.

**Comment by fxmorin** [comment]
When leaves are set to fast, they shouldn't be invisible.

**Comment by AnomalousDeity** [comment]
the leaves themselves arnt invisible its the face connected to the floor or wall that becomes transparent allowing to see through the underworld caves or through someones house

**Comment by fxmorin** [comment]
Yes although when leaves are set to fast, they are usually opaque

**Comment by 2el222** [comment]
> texture pack wise should only effect selective things such as 3d crops, 3d sun and moon, better glow berries, better vines. otherwise everything else is vanilla. Mods however im using quite a Bit, but world gen mods are oh the biomes you'll go, Promanade, JJthunder hills, better nether,better end and few structure mods such as When dungeons arise, better villages, explore the world. in total im using 231 mods.
> 
> this occurs with vanilla leaves/blocks as well, whenever its placed on the floor or side of the wall i can see though it

its not on the problem, but dont use fast leaves with betterx mods, it breaks resources of the mod group ;)
