### ISSUE TITLE
Bamboo isn't culled when it has large leaves

### ISSUE THREAD

**Issue by evhunter09** [fxmorin/MoreCulling#86]
MoreCulling currently culls the inside of bamboo when it has small or no leaves but if it has large leaves it doesn't get culled correctly. 
screenshots:
![2022-08-24_15 54 01](https://user-images.githubusercontent.com/89302916/186453305-eba718aa-df59-4f53-a4e4-773012a9cafb.png)
(this is inside a normal bamboo looking into one with leaves)
![2022-08-24_15 55 08](https://user-images.githubusercontent.com/89302916/186453464-cc032565-3ca6-48d9-94a9-c629c27ac8ab.png)
(looking into one with small leaves)

Also it culls the top/bottom of big bamboo if small bamboo is touching it (but i don't think that its possible in vanilla survival)
![2022-08-24_15 52 28](https://user-images.githubusercontent.com/89302916/186455188-d3e6b28c-fac1-42f6-93d6-076521b7f455.png)
Culling disabled:
![2022-08-24_15 52 12](https://user-images.githubusercontent.com/89302916/186455218-474980f4-7081-4ee4-beab-bcda1844e212.png)

**Comment by fxmorin** [comment]
I'll probably fix the size difference at some point. Although yes im aware of the large leaves. It's due to how the transparency scan works. I need to work on that some more although I don't have time at the moment

**Comment by evhunter09** [comment]
Its not a big issue and im pretty sure that large leaves only spawn right at the top of bamboo, and i saw the other issue about bamboo and glass, but this is slightly different. Also thanks for responding so fast

**Comment by fxmorin** [comment]
This has been fixed by accident in v0.12.0 xD
I made some large changes to account for edge case checks and it seems this was one of them, enjoy ;)
