### ISSUE TITLE
When crossing chunks,incorrect culling for glass

### ISSUE THREAD

**Issue by x-yingcan-x** [fxmorin/MoreCulling#87]
mod version 0.10.0
mc version 1.19.1
![2022-08-25_15 15 36](https://user-images.githubusercontent.com/99530733/186601219-1f99099e-2cb5-44fe-b5c0-43590c68bfa6.png)
![2022-08-25_15 15 48](https://user-images.githubusercontent.com/99530733/186601227-909365ef-103c-4c58-b374-7c38555bc910.png)

**Comment by fxmorin** [comment]
This is not caused by MoreCulling

**Comment by x-yingcan-x** [comment]
But I still hope to fix it, culling this part, as an enhanced feature
