### ISSUE TITLE
Entire chunks are culled incorrectly

### ISSUE THREAD

**Issue by AreaDenial** [fxmorin/MoreCulling#88]
0.9.1 vs 0.10.0
![more_culling_0 9 1](https://user-images.githubusercontent.com/32404366/188284670-a45e6be5-e027-445d-82e7-85c69cc176f7.png)
![more_culling_0 10 0](https://user-images.githubusercontent.com/32404366/188284676-2c108ed8-13f3-4a47-acd5-62b301219f2b.png)

**Comment by AreaDenial** [comment]
Issue seems to be caused by a different mod, DashLoader. Seems chunk information is incorrectly cached somehow, and is fixed by reloading the cache with F3+T. Closing this issue.

**Comment by fxmorin** [comment]
Well it should still be fixed. I don't have the time to do this currently
