### ISSUE TITLE
Cull the sides of map item frames

### ISSUE THREAD

**Issue by muzikbike** [fxmorin/MoreCulling#89]
The sides of map-containing item frames are coplanar with block edges and as such are fully occluded by any adjacent blocks. As such, these sides are prime candidates for being culled in such situations.

Example culling by full blocks:
![2022-09-04_00 15 58](https://user-images.githubusercontent.com/52297970/188290400-355170fb-8012-426b-bc6a-00b14d38e67c.png)
![2022-09-04_00 16 04](https://user-images.githubusercontent.com/52297970/188290401-5f415352-6bec-4407-90f4-f72334e1f761.png)
![2022-09-04_00 16 07](https://user-images.githubusercontent.com/52297970/188290402-fcaa182d-a8ca-42dd-83a1-fa8c9928ca4e.png)
![2022-09-04_00 16 27](https://user-images.githubusercontent.com/52297970/188290403-8f474593-68ca-4964-9eee-955bb9e43637.png)
![2022-09-04_00 16 30](https://user-images.githubusercontent.com/52297970/188290405-37a9d795-2e81-4d50-8fd2-93cdb216af75.png)

Example culling by other item frames:
![2022-09-04_00 16 39](https://user-images.githubusercontent.com/52297970/188290410-f949a3aa-7525-45dc-88b9-9da69bc1f7f7.png)
![2022-09-04_00 16 49](https://user-images.githubusercontent.com/52297970/188290411-62c433dc-cec4-4385-b36c-2510d63476e4.png)

It's worth noting that for some reason, map item frames also contain some inner planes that can never be seen without intersecting the frame, so it might be wise to just outright delete these faces from the model. I can provide a modified model json file if desired.

**Comment by fxmorin** [comment]
I believe the performance cost of checking the blocks is more expensive so I won't do this unless I make a block based entity system or a cached entity lookup that gets modified by block updates
