### ISSUE TITLE
Crash Log after Recent Update

### ISSUE THREAD

**Issue by ardissaps** [fxmorin/MoreCulling#9]
[Crash Log](https://paste.atlauncher.com/view/9568866b-5f49-4c27-b6e5-4f3134dae773
)
@fxmorin

**Comment by ardissaps** [comment]
https://paste.atlauncher.com/view/e4085f65-ea4a-47bf-ad0f-e6c64a26222d crash again after giving a try today

**Comment by ardissaps** [comment]
https://paste.atlauncher.com/view/e4085f65-ea4a-47bf-ad0f-e6c64a26222d crash again after giving a try today

**Comment by ardissaps** [comment]
it crashed after log sponge sponge thing idk

**Comment by fxmorin** [comment]
Yes im aware that sodium does not currently work

**Comment by fxmorin** [comment]
#8

**Comment by ardissaps** [comment]
Finally it work, now I need mod that utilize these poor bamboo, then build bamboo house and live in peace with panda
