### ISSUE TITLE
Pressure plates should cull the tops of fences and walls

### ISSUE THREAD

**Issue by muzikbike** [fxmorin/MoreCulling#91]
This might be too rare to special-case (https://github.com/CaffeineMC/sodium-fabric/issues/878), but could be implemented if considered worthwhile for this project.

**Comment by fxmorin** [comment]
Fixed in v0.13.0 ;)

**Comment by muzikbike** [comment]
I tested this in a subsequent version, and it doesn't seem to work anymore? I'll need to check again some time soon.
