### ISSUE TITLE
models bug

### ISSUE THREAD

**Issue by lostopkk** [fxmorin/MoreCulling#92]
### I was playing until I noticed that some models work normally others give this bug, I don't know why else it happens with most decoration mods

Mod used example: Adorn

### Moreculling on:
![image](https://user-images.githubusercontent.com/50776714/189765418-af150923-2190-4b04-b6a1-98521d8cc3c9.png)
### Moreculling off:
![image](https://user-images.githubusercontent.com/50776714/189765471-8c8c8610-3e2a-4ed6-9cc6-fec0a704fbfe.png)

**Comment by lostopkk** [comment]
another example:
![image](https://user-images.githubusercontent.com/50776714/189765828-a0090200-b7d1-4bab-8f19-f96db617820a.png)

**Comment by fxmorin** [comment]
You can disable adorn in the mod settings. No other good way around it
