### ISSUE TITLE
Ability to disable culling of glass panes by glass

### ISSUE THREAD

**Issue by muzikbike** [fxmorin/MoreCulling#93]
Unlike the other culling additions made by this mod, this has a clear visual effect on models in game. I'm personally not sure if I like this change or not, as it seems inconsistent with other blocks and their culling behaviour, so a config option to turn it on or off may be advisable.

**Comment by fxmorin** [comment]
https://github.com/fxmorin/MoreCullingExtra
Made an extra mod for it
