### ISSUE TITLE
Glass pane culling by glass doesn't actually cull the face

### ISSUE THREAD

**Issue by muzikbike** [fxmorin/MoreCulling#94]
It seems that instead, that edge of the glass pane just uses the glass texture instead. This is hard to see for normal glass panes against normal glass, but mixing glass types (such as glass panes against tinted glass) make it more obvious:
![2022-09-12_23 15 38](https://user-images.githubusercontent.com/52297970/189770060-f7c779ae-7a51-40c6-92da-4fd54e75af72.png)
![2022-09-12_23 15 47](https://user-images.githubusercontent.com/52297970/189770065-21865b8d-a62b-47f9-ae93-0700a3f6d9dc.png)

**Comment by fxmorin** [comment]
https://github.com/fxmorin/MoreCullingExtra
