### ISSUE TITLE
Allow beacon glass to cull against glass blocks and other beacons

### ISSUE THREAD

**Issue by muzikbike** [fxmorin/MoreCulling#96]
By default, the beacon model doesn't define cullface parameters on its outward faces. However, even if a resource pack fixes this, the glass faces of the beacon don't cull against other beacon blocks, nor do they cull against glass blocks. This is inconsistent with how glass blocks cull each other.

A resource pack to test this with can be found attached to https://bugs.mojang.com/browse/MC-239142.

![2022-09-13_06 54 41](https://user-images.githubusercontent.com/52297970/189821124-30e67d4e-8cb8-4bec-9be3-d07dbe678103.png)
![2022-09-13_06 54 43](https://user-images.githubusercontent.com/52297970/189821136-b64482d3-57b6-4755-8d93-2bee31de68cd.png)

This is vanilla bug https://bugs.mojang.com/browse/MC-105274.

**Comment by fxmorin** [comment]
Ask and you shall receive: https://github.com/fxmorin/MoreCullingExtra
